### ISSUE TITLE
Atomic operations support

### ISSUE THREAD

**Issue by kidambisrinivas** [yinqiwen/ardb#108]
Hi,

May I check with you if ardb supports the redis commands multi, exec and guarantee that all the keys in the transaction block will be operated upon only by the current client's request?

Thanks in advance.

**Comment by hnbanh** [comment]
Hi yinqiwen, 

I dont know about performance of transaction/pipeline but as I know, it's not good as expected. I get data by pipelining always slower than I get data sequentially (5-30keys).
I used Jedis 2.6.0, Ardb 0.8.1.

Thanks,

**Comment by yinqiwen** [comment]
All commands received from one network connection would be executed in only one thread in ardb. Is there only one tcp connection with pipelining in jedis?

**Comment by hnbanh** [comment]
Yes, it's only 1 connection with pipelining.
More info: https://github.com/xetorthio/jedis

This is how I use pipeline to multi-get hash data from Ardb with Jedis.
JedisPool jedisPool = new JedisPool(.....); 
Jedis jedis = jedisPool.getResource(); 
Pipeline p = jedis.pipelined();
for (Integer id : ids) {
	p.hgetAll("test:" + id);
}
p.syncAndReturnAll();
// return connection

In my test case, If ids.size() == 1, It just takes less than 1ms to get the result. But ids.size() == 2 or more, it's performed in arround 40ms (????)

**Comment by yinqiwen** [comment]
Can you test with `redis-benchamrk` with pipeline options?

**Comment by hnbanh** [comment]
./redis-benchmark -h <host> -p <port> -P 1 -t get -q
GET: 17211.71 requests per second

./redis-benchmark -h <host> -p <port> -P 2 -t get -q
GET: 2396.36 requests per second

./redis-benchmark -h <host> -p <port> -P 3 -t get -q
GET: 3585.51 requests per second

**Comment by hnbanh** [comment]
But from P > 15, it seems better.

./redis-benchmark -h [host] -p [port] -P 15 -t get -q
GET: 18050.54 requests per second

./redis-benchmark -h [host] -p [port] -P 16 -t get -q
GET: 19157.09 requests per second

./redis-benchmark -h [host] -p [port] -P 17 -t get -q
GET: 20449.90 requests per second

./redis-benchmark -h [host] -p [port] -P 20 -t get -q
GET: 24096.39 requests per second

./redis-benchmark -h [host] -p [port] -P 50 -t get -q
GET: 52083.33 requests per second

**Comment by yinqiwen** [comment]
Can you use latest code to test? 
I got different  benchmark result with latest code:
./redis-benchmark  -p 36379 -t get 
====== GET ======
  100000 requests completed in 1.30 seconds
  50 parallel clients
  3 bytes payload
  keep alive: 1

99.98% <= 1 milliseconds
100.00% <= 1 milliseconds
76628.36 requests per second

./redis-benchmark  -p 36379 -t get  -P 2
====== GET ======
  100000 requests completed in 0.68 seconds
  50 parallel clients
  3 bytes payload
  keep alive: 1

100.00% <= 0 milliseconds
146627.56 requests per second

./redis-benchmark  -p 36379 -t get  -P 3
====== GET ======
  100000 requests completed in 0.58 seconds
  50 parallel clients
  3 bytes payload
  keep alive: 1

95.51% <= 1 milliseconds
100.00% <= 2 milliseconds
100.00% <= 2 milliseconds
173310.22 requests per second

**Comment by hnbanh** [comment]
Sorry for late reply, I just return from my vacation.

I used latest code (both download source from https://github.com/yinqiwen/ardb/archive/v0.8.1.tar.gz or git clone https://github.com/yinqiwen/ardb.git)

Storage engine is lmdb and default config.
