### ISSUE TITLE
Feature Request: Support for ForestDB

### ISSUE THREAD

**Issue by gottlike** [yinqiwen/ardb#112]
Recently Couchbase released a beta of their new storage engine ForestDB. Performance looks really promising: https://github.com/couchbaselabs/forestdb/wiki/Performance-Results

Maybe ardb could support it in a future release.

**Comment by bgelfand** [comment]
Any progress on this? I see some bits involving the ForestDB engine but it doesn't appear complete.

**Comment by yinqiwen** [comment]
Still  waiting for ForestDB's GA release.

**Comment by bgelfand** [comment]
Ok, and I know it is me and not the code, but how do I start ardb so it can start taking requests?

**Comment by yinqiwen** [comment]
forestdb still have wired behavior that delete data in iterator success, but the deleted data could be read later, which makes it can NOT pass the lua test suite.

**Comment by yinqiwen** [comment]
complete by https://github.com/yinqiwen/ardb/commit/a19eba064001075c1cd5c49ed72a2f387b2df3e2
