### ISSUE TITLE
srandmember does not complete

### ISSUE THREAD

**Issue by amitkarmakar13** [yinqiwen/ardb#150]
For some reasons srandmember is not completing. I have tried accessing ardb instance using jedis and redis-cli and in both cases the command never completes. 
Is there something i may be missing?

**Comment by yinqiwen** [comment]
Is the set not exist ? There is a bug that ardb do not return if the set is not exist or empty for `srandmember`， just commit a fix for it.

**Comment by amitkarmakar13** [comment]
The set does exist and has enough elements for srandmember to return a value.

**Comment by yinqiwen** [comment]
Can u test again with latest code from github?

**Comment by amitkarmakar13** [comment]
smember does return values now. but the count parameter seems to have no effect. smember is always returning a single element no matter what count is specified. I tested out with the latest code

**Comment by yinqiwen** [comment]
yes， it's a missing feature, i'll implement it later.
