### ISSUE TITLE
bitop 操作bug

### ISSUE THREAD

**Issue by ofeng** [yinqiwen/ardb#151]
SETBIT test1 100000000 1
SETOP OR result test1 test2

当test1 超过1千万时,   test2 不存在时 result 会返回0

**Comment by ofeng** [comment]
127.0.0.1:16379> SETBIT smallbit 10 1
(integer) 0
127.0.0.1:16379> SETBIT largebit 10000000 1
(integer) 0
127.0.0.1:16379> BITCOUNT smallbit
(integer) 1
127.0.0.1:16379> BITCOUNT largebit
(integer) 1
127.0.0.1:16379> BITOP or target smallbit largebit
(error) ERR Operation against a key holding the wrong kind of value.
127.0.0.1:16379> BITOP or target1 largebit noexist
(integer) 0
127.0.0.1:16379> BITCOUNT target1
(integer) 0

**Comment by yinqiwen** [comment]
Currently, ardb can NOT handle different value type（bitset/string） for bitop
