### ISSUE TITLE
How do i specify how much memory to use in ardb.conf? 

### ISSUE THREAD

**Issue by hwongcom** [yinqiwen/ardb#152]
I checked the ardb.conf... doesnt say have any comments?

**Comment by hwongcom** [comment]
how do i show statistics of ardb?

**Comment by hwongcom** [comment]
how do i show last command ran in ardb or last few queries ran?

**Comment by yinqiwen** [comment]
There is no such config to explicit limit memory usage, and no command to show last command executed.

**Comment by hwongcom** [comment]
I mean... can I limit ardb to use only 1GB or something?

**Comment by yinqiwen** [comment]
You can only modify storage engine's configuration to limit the storage engine's memory usage. 
And not all storage engine provide such configurations.

**Comment by refaelos** [comment]
@yinqiwen so there's no limit on memory? I mean, I can have 4GB of RAM and still save 50GB of data?

I know it might be a stupid question but is ardb just a redis interface to persistent on-disk DBs?

**Comment by yinqiwen** [comment]
@refaelos yes, the data is stored on disk.
