### ISSUE TITLE
Which is faster, gzipped flat file storage and retrieval randomly or ardb snappy leveldb storage?

### ISSUE THREAD

**Issue by hwongcom** [yinqiwen/ardb#153]
Do you know which is faster? Any benchmark results to simulate random accessing compressed gzipped files or ardb snappy leveldb storage?

Please give opinion on how to generate random 100mil 7k gzipped, (normal 35kb) html average ascii file.

Thanks

**Comment by yinqiwen** [comment]
You can test it yourself.
