### ISSUE TITLE
flushall not flushing everything?

### ISSUE THREAD

**Issue by bpytlik** [yinqiwen/ardb#154]
I'm not sure what the title of this should be. It's either that flushall misses things, it returns before it's finished, or that lua scripts (at least ones with flushall) aren't atomic in ardb.

Here's the setup:
I have one process that's trying to put things into an ardb database.
I have another process that runs this script periodically:
```
redis.call('flushall')
return redis.call('keys', '*')
```

I'd expect this script to return no values because the database has flushed just prior to the keys call in a script that's supposed to be transactional. Typically, this is the case. Occasionally though, I see results returning from the script. I don't know whether the value(s) are ones that were not cleared or ones that were inserted between the call to flushall and the call to keys.

**Comment by yinqiwen** [comment]
Ardb is a multi thread server, so lua script is not atomic.

**Comment by bpytlik** [comment]
So if I set ardb to run w/ a single thread, then I should not see this as an issue, correct?

**Comment by yinqiwen** [comment]
yes
