### ISSUE TITLE
keys * command failed from redis-cli

### ISSUE THREAD

**Issue by bpytlik** [yinqiwen/ardb#158]
I tried to run the `keys *` command from a redis-cli. The command took quite a while to run, and then the client exited with:
```
127.0.0.1:6382> keys *
Error: Protocol error, got "a" as reply type byte
```
The on disk (leveldb) representation is about 900M in size.

I'm not sure what info is useful to gather, but I'm happy to gather what I can.

**Comment by bpytlik** [comment]
Also, when I looked at the output of the `info` command, I saw this:
```
# Keyspace
db0:keys=-1
```
Which seems bad.

**Comment by yinqiwen** [comment]
There is a issue https://github.com/yinqiwen/ardb/commit/a56821d6173f08f6d8f00a47b240246198e796b2 for reply codec, is the fix already in your server?

**Comment by yinqiwen** [comment]
Since it's not easy to count the keys count in leveldb/rocksdb,  so use -1 instead.

**Comment by bpytlik** [comment]
It should be, we're running git hash `06b6053fecda32a79625a9cace8227d20ad69e1d`, so gate tip.

Ah, I didn't realize that, thanks for the explanation.
