### ISSUE TITLE
ardb silently ignores lengthy elements in zset with LMDB

### ISSUE THREAD

**Issue by lamoz** [yinqiwen/ardb#159]
It seems that when i am adding long elements into zset ardb says ok and just silently ignore zadd command.
for example:
$ redis-cli -p 16379
127.0.0.1:16379> zadd mykey 1 zzzzzz<600 of 'z' follows>
(integer) 1
127.0.0.1:16379> zscan mykey 0 MATCH *
1) "0"
2) 1) "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"
   2) "1"
127.0.0.1:16379> zadd mykey 1 zzzzzz<599 of 'z' follows>
(integer) 1
127.0.0.1:16379> zscan mykey 0 MATCH *
1) "0"
2) (empty list or set)

There is no strange things in debug log
my ziplist settings in the config are:
zset-max-ziplist-entries 1
zset-max-ziplist-value   1

It seems to me that LMDB's key length limit plays here. See https://gitorious.org/mdb/mdb/source/3368d1f5e243225cba4d730fba19ff600798ebe3:libraries/liblmdb/mdb.c#L513
I have upgraded LMDB to 0.9.14 as it fixes some important bugs. 0.9.13 behaves the same regarding this issues tho.

**Comment by lamoz** [comment]
github chewed my report. The first time I zadd element with 'z'x600, second time I zadd 'z'x599

**Comment by yinqiwen** [comment]
Fixed
