### ISSUE TITLE
Using ZSETs for indexes

### ISSUE THREAD

**Issue by lamoz** [yinqiwen/ardb#161]
Hi! I am using ordered sets as indexes for my data. As far as I can see ZRANGE, ZRANGEBYLEX and ZRANGEBYSCORE in ardb return data strictly ordered by corresponding field (score and member), which is not the case with Redis.
Redis docs says for ZRANGEBYLEX:
> If the elements in the sorted set have different scores, the returned elements are unspecified.

It would be reasonable if I could rely on this ardb's behavior since ardb uses 2n+1 records (I dont completely understand ardb encodings) in underlying engine (LMDB in my case). I would be using 2n+1 records for 2n index records then :)
Is this behavior intentional? Can I rely on it?

PS: ardb is brilliant, many thanks to all involved developers!

**Comment by yinqiwen** [comment]
Fixed.

**Comment by lamoz** [comment]
Im sorry for commenting closed ticket. But what is the answer? Is this behavior reliable?

**Comment by yinqiwen** [comment]
Yes, it's reliable.
Because all the storage engine use  tree like structure(B+ tree, LSMtree, etc), all the data would be ordered.
