### ISSUE TITLE
broken zrangebylex ordering with LMDB

### ISSUE THREAD

**Issue by lamoz** [yinqiwen/ardb#162]
I generate DB using perl script for both Redis and ardb ( with LMDB engine ):
```perl
my $client = RedisDB->new( host => 'localhost', port => 26379 );
$client->execute('SELECT', 10);
$client->execute( 'ZADD', 'key', 0, sprintf("%02d", $_) ) for 1..10;
```

Redis:
```
127.0.0.1:6379> select 10
OK
127.0.0.1:6379[10]> zrangebylex key - [99
 1) "01"
 2) "02"
 3) "03"
 4) "04"
 5) "05"
 6) "06"
 7) "07"
 8) "08"
 9) "09"
10) "10"
```

ardb:
```
127.0.0.1:26379> select 10
OK
127.0.0.1:26379[10]> zrangebylex key - [99
 1) "10"
 2) "01"
 3) "02"
 4) "03"
 5) "04"
 6) "05"
 7) "06"
 8) "07"
 9) "08"
10) "09"
```
The result is identical with zset-max-ziplist-* set to 1 and 100.
Seems to be a bug.

**Comment by lamoz** [comment]
I believe this is due to https://github.com/yinqiwen/ardb/blob/master/src/command/t_zset.cpp#L278
```
element.SetString(cmd.GetArguments()[i + 1], true);
```
Why "true" is there?

**Comment by yinqiwen** [comment]
The `10` would be encoded to integer, while `01` would be encoded as a string. This would save many disk space for many integer values.

**Comment by lamoz** [comment]
Oh I see. But is this behavior correct? I suspect that element is used for lexical ordering here. Working zrangebylex is more important than saving disk space I think.

**Comment by yinqiwen** [comment]
I'll add a configuration for it.

**Comment by yinqiwen** [comment]
Fixed
