### ISSUE TITLE
cross compile err

### ISSUE THREAD

**Issue by darcyg** [yinqiwen/ardb#163]
我想把ardb移植到openwrt环境下。
但是现在Makefile很不规范。
能否用CMake做编译。这样交叉编译能简单很多

**Comment by yinqiwen** [comment]
你可以fork出来自己写一个cmake，当前的Makefile还是相对很简单，移植到cmake也不困难。
当前用makefile的主要原因是cmake应用还不够广泛，还有很多环境是没有安装cmake的。
