### ISSUE TITLE
Lua script non-atomicity needs to be clearly documented

### ISSUE THREAD

**Issue by bpytlik** [yinqiwen/ardb#164]
From redis documentation:
```
Atomicity of scripts
Redis uses the same Lua interpreter to run all the commands. Also Redis guarantees that a script is executed in an atomic way: no other script or Redis command will be executed while a script is being executed. This semantics is very similar to the one of MULTI / EXEC. From the point of view of all the other clients the effects of a script are either still not visible or already completed.
However this also means that executing slow scripts is not a good idea. It is not hard to create fast scripts, as the script overhead is very low, but if you are going to use slow scripts you should be aware that while the script is running no other client can execute commands since the server is busy.
```
If ardb does not properly implement this critical feature of lua scripting (see the response here: https://github.com/yinqiwen/ardb/issues/154), then that limitation needs to be clearly documented. It's not reasonable to say 
```
Full redis-protocol compatibility
```
without further documenting the limitations of lua scripting.
This spot seems like a reasonable location to add the documentation:
https://github.com/yinqiwen/ardb/wiki/ARDB-Commands.

I'm guessing the same issue that exists for multi/exec. If that's true, that should be documented as well.

**Comment by yinqiwen** [comment]
There is a global lock for `exec`, so no such issue  for multi/exec.
https://github.com/yinqiwen/ardb/blob/master/src/command/transaction.cpp#L74

**Comment by yinqiwen** [comment]
I'll add a global lock for lua script too.

**Comment by yinqiwen** [comment]
Added global lock for lua interceptor.
