### ISSUE TITLE
如何释放空间？

### ISSUE THREAD

**Issue by 6api** [yinqiwen/ardb#165]
测试hset 100万条，然后hdel删除，看数据目录里文件大小还是没变
测试mysql同样也是没变，但MYSQL用optimize table就可以释放了
另外写了一些测试，与SSDB相比，性能稍差些，但我更喜欢这个，优点是兼容REDIS API更好
唯一的毛病就是硬盘空间老不释放

**Comment by yinqiwen** [comment]
use `compactall` command
