### ISSUE TITLE
No error checks for LMDB

### ISSUE THREAD

**Issue by lamoz** [yinqiwen/ardb#166]
I've just made a configuration error, set lmdb.database_max_size to 1T (literally). Started ardb, then putted some thousand records which exceeded my limit (which turned out to be 1MB I think). 
There were no errors in log. It seems that there is missing error checks. This is very confusing. The more confusing thing that some data gets into storage even when using transactions! Dont know whether this is lmdb's or Ardb's bug, but lmdb should return errorcode according to their documentation.

This is how I put data into Ardb:
```
#!/usr/bin/env perl

use RedisDB;
my $client = RedisDB->new( host => 'localhost', port => 16379 );
$client->execute( 'MULTI' );
$client->execute( 'SET', $_, 'X' x 1000 ) for 1..1000;
$client->execute( 'EXEC' );
```

Same result when not using MULTI

**Comment by yinqiwen** [comment]
add check log for most lmdb api  invocation.

**Comment by lamoz** [comment]
errors are written to log now, but redis-cli gets OK even when size limit reached "LMDB operation:mdb_txn_commit(txn) error:MDB_MAP_FULL: Environment mapsize limit reached". Im not using MULTI in this case

**Comment by yinqiwen** [comment]
Current lmdb engine dispatch all write operations into another thread, and return immediately, so all write operations would return OK.

**Comment by lamoz** [comment]
Same for LevelDB/RocksDB/others? It should be definetely described in readme

**Comment by bendiken** [comment]
@yinqiwen, note that there is now a comprehensive [C++ wrapper for LMDB](https://github.com/bendiken/lmdbxx), which includes an error-checked procedural interface in case that might be useful for Ardb. The wrapper is a single header file released into the public domain, making it easy to drop into any project without headaches about dependencies or licensing.

**Comment by yinqiwen** [comment]
@lamoz  only LMDB have this issue.
@bendiken  there is a limit in IMDB which one thread can only have one transaction at the same time, that's the reason why ardb  dispatch all write operations into another thread.
