### ISSUE TITLE
FlushAll command with RocksDB storage engine

### ISSUE THREAD

**Issue by pyros2097** [yinqiwen/ardb#167]
I have a zset with some scores and members and after I do a flush all the ```keys *``` shows no keys in redis but when I run my test cases which add 1 member to the zset and then read it it shows all the old scores and members?

Do you have to compact it after flush? It seems to me that the data isn't completed removed?

**Comment by yinqiwen** [comment]
What's the command do you exec to flush all keys? And what's the commands in the test cases?

There is no need to compact after flush.

**Comment by pyros2097** [comment]
I use ```flushall``
I'm getting these errors in log
```
[32408] 04-08 11:46:55,517 ERROR No handler found for:compact with size:7 in connection:289
[32408] 04-08 11:46:55,517 ERROR Invalid command's ascii codes:99 111 109 112 97 99 116
```
The commands in the test cases are zadd, zrem and zrange to add and remove a single member and check if the zset size is 1. But some older test case data with same key and has 6 members in it is being loaded so when a zrange is done to test the size I get 7

**Comment by pyros2097** [comment]
Wait My Bad... It seems the test case loads the other data in the middle but when I was running the tests with redis they were all passing...
