### ISSUE TITLE
zunionstore and sunionstore broken

### ISSUE THREAD

**Issue by borg286** [yinqiwen/ardb#171]
When destination is same as one of the source sets it is not included

127.0.0.1:6379> zadd myset 1 1 2 2 3 3
(integer) 3
127.0.0.1:6379> zadd otherset 3 3 4 4 5 5
(integer) 3
127.0.0.1:6379> zunionstore myset 2 myset otherset
(integer) 3
127.0.0.1:6379> zrange myset 0 999
1) "3"
2) "4"
3) "5"
127.0.0.1:6379> 

It should be 1, 2, 3, 4, 5

**Comment by borg286** [comment]
I believe the bug is on line 
    int Ardb::ZUnionStore(Context& ctx, RedisCommandFrame& cmd)
    {
        ZSetMergeOptions options;
        if (!options.Parse(cmd.GetArguments(), 1))
        {
            fill_error_reply(ctx.reply, "Invalid argument");
            return 0;
        }
        int err = DeleteKey(ctx, cmd.GetArguments()[0]);   //<----- Should first check if destination is one of the sources

**Comment by borg286** [comment]
This is how redis does it
https://github.com/antirez/redis/blob/832b0c7ccef0e7e11e0663530367de1d3fb9a959/src/t_zset.c#L1875
It seems that we should first lookup the type of the destination to verify either it's empty or a zset. We should probably do the same

**Comment by kakysha** [comment]
https://github.com/yinqiwen/ardb/issues/168

**Comment by borg286** [comment]
No. This is a bug in the ZUnionStore code wherein it doesn't check the destination before deleting it. This corner case is when one of the sources is the same as the destination.
#168 is about ordering of zset elements. completely orthogonal.

**Comment by yinqiwen** [comment]
In ardb, it would clear all `store`destination  key before execute `union/inter/diff` store operations.

It's difficult to implement this feature like redis  which would store all calculated data in memory first. 
IMO,it's better to forbid duplicated destination key in input keys.

**Comment by borg286** [comment]
That would prevent a rolling union or a rolling subtraction. I very much
would like such a feature. Why not simply check I'd the destination is one
of the sources and if so then use that data in the union/inter/diff's first
pass in the for loop.

**Comment by yinqiwen** [comment]
fixed in 0.9
