### ISSUE TITLE
ltrim resulting in empty list causes unexpected redis reply type:0

### ISSUE THREAD

**Issue by mayankgupta173** [yinqiwen/ardb#172]
lpush 1 hi
lpush 1 bye
ltrim 1 0 1
> ERROR Recv unexpected redis reply type:0

no response from server.

**Comment by yinqiwen** [comment]
fixed

**Comment by mayankgupta173** [comment]
Found another one: spop key n -- the 'n' argument isn't supported.

**Comment by yinqiwen** [comment]
According redis's doc, it's not available in current redis version. I'll add the 'n' argument later.
http://redis.io/commands/spop
