### ISSUE TITLE
info command not returning correct result

### ISSUE THREAD

**Issue by mayankgupta173** [yinqiwen/ardb#174]
redis-cli info
> # Keyspace
> db0:keys=-1
> db1:keys=-1
> db2:keys=-1
> db3:keys=-1
> db4:keys=-1
> db5:keys=-1
> db11:keys=-1

when in fact db0 has greater than 250,000 keys and db1 > 1M, and db11 has been 'flushdb'ed.

**Comment by yinqiwen** [comment]
There is no direct & efficient way to get total keys number from leveldb/rocksdb/lmdb.  The `Keyspace` output only shows that used dbs.
