### ISSUE TITLE
very high cpu load...

### ISSUE THREAD

**Issue by hwongcom** [yinqiwen/ardb#175]
i have extremely high cpu load using ardb... how can i check what is happening?

i shifted from using mysql to ardb

**Comment by yinqiwen** [comment]
u can use gdb attach running process to see which thread is busy

**Comment by hshh** [comment]
Same here, run on FreeBSD 10.2 amd64.
Here is gdb info,

(gdb)  info threads
  7 Thread 801c06400 (LWP 100946/ardb-server.gcc48)  0x00000008014cff8a in _kevent () from /lib/libc.so.7
  6 Thread 801c06c00 (LWP 100935/ardb-server.gcc48)  0x00000008014cff8a in _kevent () from /lib/libc.so.7
  5 Thread 801c07800 (LWP 101060/ardb-server.gcc48)  0x00000008014cff8a in _kevent () from /lib/libc.so.7
  4 Thread 801c07c00 (LWP 101061/ardb-server.gcc48)  0x00000008014cff8a in _kevent () from /lib/libc.so.7
  3 Thread 801c08000 (LWP 101063/ardb-server.gcc48)  0x00000008014cff8a in _kevent () from /lib/libc.so.7
  2 Thread 801c08400 (LWP 101066/ardb-server.gcc48)  0x00000008014cff8a in _kevent () from /lib/libc.so.7
* 1 Thread 801c08800 (LWP 101070/ardb-server.gcc48)  0x00000008014cff8a in _kevent () from /lib/libc.so.7
(gdb) bt
#0  0x00000008014cff8a in _kevent () from /lib/libc.so.7
#1  0x00000008009d22c2 in pthread_suspend_all_np () from /lib/libthr.so.3
#2  0x000000000048a4e0 in ?? ()
#3  0x0000000000000003 in ?? ()
#4  0x0000000000000000 in ?? ()
(gdb) th
thbreak  thread   
(gdb) thread 2
[Switching to thread 2 (Thread 801c08400 (LWP 101066/ardb-server.gcc48))]#0  0x00000008014cff8a in _kevent () from /lib/libc.so.7
(gdb) bt
#0  0x00000008014cff8a in _kevent () from /lib/libc.so.7
#1  0x00000008009d22c2 in pthread_suspend_all_np () from /lib/libthr.so.3
#2  0x000000000048a4e0 in ?? ()
#3  0x0000000000000003 in ?? ()
#4  0x0000000000000000 in ?? ()
(gdb) thread 3
[Switching to thread 3 (Thread 801c08000 (LWP 101063/ardb-server.gcc48))]#0  0x00000008014cff8a in _kevent () from /lib/libc.so.7
(gdb) bt
#0  0x00000008014cff8a in _kevent () from /lib/libc.so.7
#1  0x00000008009d22c2 in pthread_suspend_all_np () from /lib/libthr.so.3
#2  0x000000000048a4e0 in ?? ()
#3  0x0000000000000003 in ?? ()
#4  0x0000000000000001 in ?? ()
#5  0x0000000000000000 in ?? ()
(gdb) thread 4
[Switching to thread 4 (Thread 801c07c00 (LWP 101061/ardb-server.gcc48))]#0  0x00000008014cff8a in _kevent () from /lib/libc.so.7
(gdb) bt
#0  0x00000008014cff8a in _kevent () from /lib/libc.so.7
#1  0x00000008009d22c2 in pthread_suspend_all_np () from /lib/libthr.so.3
#2  0x000000000048a4e0 in ?? ()
#3  0x0000000000000003 in ?? ()
#4  0x0000000000000004 in ?? ()
#5  0x0000000000000000 in ?? ()
(gdb) thread 5
[Switching to thread 5 (Thread 801c07800 (LWP 101060/ardb-server.gcc48))]#0  0x00000008014cff8a in _kevent () from /lib/libc.so.7
(gdb) bt
#0  0x00000008014cff8a in _kevent () from /lib/libc.so.7
#1  0x00000008009d22c2 in pthread_suspend_all_np () from /lib/libthr.so.3
#2  0x000000000048a4e0 in ?? ()
#3  0x0000000000000003 in ?? ()
#4  0x0000000000000002 in ?? ()
#5  0x0000000000000000 in ?? ()
(gdb) thread 6
[Switching to thread 6 (Thread 801c06c00 (LWP 100935/ardb-server.gcc48))]#0  0x00000008014cff8a in _kevent () from /lib/libc.so.7
(gdb) bt
#0  0x00000008014cff8a in _kevent () from /lib/libc.so.7
#1  0x00000008009d22c2 in pthread_suspend_all_np () from /lib/libthr.so.3
#2  0x000000000048a4e0 in ?? ()
#3  0x0000000000000003 in ?? ()
#4  0x0000000000000002 in ?? ()
#5  0x0000000000000000 in ?? ()
(gdb) thread 7
[Switching to thread 7 (Thread 801c06400 (LWP 100946/ardb-server.gcc48))]#0  0x00000008014cff8a in _kevent () from /lib/libc.so.7
(gdb) bt
#0  0x00000008014cff8a in _kevent () from /lib/libc.so.7
#1  0x00000008009d22c2 in pthread_suspend_all_np () from /lib/libthr.so.3
#2  0x000000000048a4e0 in ?? ()
#3  0x0000000000000003 in ?? ()
#4  0x0000000000000002 in ?? ()
#5  0x0000000000000000 in ?? ()
