### ISSUE TITLE
HLL pfcount with non-exist-key

### ISSUE THREAD

**Issue by hnbanh** [yinqiwen/ardb#177]
With Ardb
./redis-cli -p 16379
127.0.0.1:16379> pfcount non-exist-key
(error) WRONGTYPE Key is not a valid HyperLogLog string value.

With Redis
./redis-cli -p 6379
127.0.0.1:6379> pfcount non-exist-key
(integer) 0

I think we dont need to check the key exist before call pfcount. In case HLL has data, it works well.

**Comment by yinqiwen** [comment]
fixed
