### ISSUE TITLE
Possible improvement of RocksDB's configuration

### ISSUE THREAD

**Issue by igorcanadi** [yinqiwen/ardb#180]
Hi,

I noticed that in default configuration you set RocksDB's write_buffer_size to 128M:
https://github.com/yinqiwen/ardb/blob/master/ardb.conf#L71

If you increase write_buffer_size it is also advisable to increase L1 size (we recommend setting L0 size to be about the same as L1). Default size of L1 is 10MB, while L0 would be 128MB \* 4 (4 is the default value of level0_file_num_compaction_trigger), which is 512MB.

TL;DR you might get better performance if you set `max_bytes_for_level_base` to 512MB.

For more details you can refer to our Tuning guide: https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide

Also, I noticed that you call a function `OptimizeLevelStyleCompaction` after you set your write buffer size. I think this function will overwrite the configuration that you set previously, as you can see here: https://github.com/facebook/rocksdb/blob/master/util/options.cc#L602

Feel free to let me know if you have any further questions.

**Comment by yinqiwen** [comment]
u are right about `OptimizeLevelStyleCompaction`, i did not notice that. 
There is too many configurations for rocksdb which makes it very hard to tunn, in our production env, we set write_buffer_size 512M at first, and there is some period compact ops in rocksdb which make all server hang for while.  After that, we decrease the write_buffer_size to 128M, it seems reduce a liittle hang time when rocksdb compacting itselt.

**Comment by igorcanadi** [comment]
If you set `max_bytes_for_level_base` to a bigger number, you might see much fewer (or no) hanging.

There are very many configuration options, I agree, but there are maybe 3, 4 very important ones. Others are mostly for turning some advanced features that most people don't need.
