### ISSUE TITLE
make ------Error Help !

### ISSUE THREAD

**Issue by HorizonWolf** [yinqiwen/ardb#181]
rm -f ../test/test_suite.o;rm -f ardb-test
echo ">>>>> Building SNAPPY" && \
	cd /usr/local/ardb-master/src/../deps && \
	tar zxf /usr/local/ardb-master/src/../deps/snappy-1.1.2.tar.gz && \
	cd /usr/local/ardb-master/src/../deps/snappy-1.1.2 && \
	./configure CXXFLAGS=""    > configure.out && \
	make libsnappy.la && \
	echo "<<<<< Done building SNAPPY"
>>>>> Building SNAPPY
make[2]: Entering directory `/usr/local/ardb-master/deps/snappy-1.1.2'
source='snappy.cc' object='snappy.lo' libtool=yes \
	DEPDIR=.deps depmode=none /bin/sh ./depcomp \
	/bin/sh ./libtool --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.      -c -o snappy.lo snappy.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -c snappy.cc  -o .libs/snappy.o
./libtool: line 1125: g++: command not found
make[2]: *** [snappy.lo] Error 1
make[2]: Leaving directory `/usr/local/ardb-master/deps/snappy-1.1.2'
make[1]: *** [/usr/local/ardb-master/src/../deps/snappy-1.1.2/.libs/libsnappy.a] Error 2
make[1]: Leaving directory `/usr/local/ardb-master/src'
make: *** [all] Error 2

**Comment by yinqiwen** [comment]
u have no g++ installed in your env.

**Comment by HorizonWolf** [comment]
thank you !
