### ISSUE TITLE
new  make ------Error Help !

### ISSUE THREAD

**Issue by HorizonWolf** [yinqiwen/ardb#182]
echo ">>>>> Building JEMALLOC" && \
	cd /usr/local/ardb/src/../deps && \
	tar jxf /usr/local/ardb/src/../deps/jemalloc-3.6.0.tar.bz2 && \
	cd /usr/local/ardb/src/../deps/jemalloc-3.6.0 && \
	patch < ../../jemalloc.patch && \
	autoconf configure.ac > configure 2> autoconf.out && \
	./configure    > configure.out && \
	make build_lib_static && \
	echo "<<<<< Done building JEMALLOC"
>>>>> Building JEMALLOC
patching file configure.ac
make[1]: *** [/usr/local/ardb/src/../deps/jemalloc-3.6.0/lib/libjemalloc.a] Error 127
make[1]: Leaving directory `/usr/local/ardb/src'
make: *** [all] Error 2
-----------------------------------------------------------------------------------------------------------------
安装 gcc version 4.8.2 (GCC) 后， 出现 jemalloc-3.6.0的错误，但是 jemalloc-3.6.0/lib/libjemalloc.a 目录里没有， 求帮助！

**Comment by yinqiwen** [comment]
check your env if `autoconf` or `patch` installed.
