### ISSUE TITLE
segfault on command during sync

### ISSUE THREAD

**Issue by pedigree** [yinqiwen/ardb#183]
I've created a SSL tunnel from a site to AWS (2.8.19) and connect to ardb (0-.8.6 wiretiger on x64 ubuntu 14.04.02)  I run a slaveof and it connects and then segfaults if I type "info" into the CLI twice. The "terminate called after throwing an instance of 'std::bad_alloc'  what():  std::bad_alloc" happened after the 2nd time I typed info

It does not core dump if I leave the cli alone while it syncs

This is the log/bt from gdb

root@ardb1:/var/log/ardb# gdb ardb-server    
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ardb-server...done.
(gdb) run /etc/ardb.conf
Starting program: /usr/local/bin/ardb-server /etc/ardb.conf
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19-gdb.py", line 63, in <module>
    from libstdcxx.v6.printers import register_libstdcxx_printers
ImportError: No module named 'libstdcxx'
[50238] 06-19 11:11:14,979 INFO Start init storage engine.
[New Thread 0x7ffff5fff700 (LWP 50242)]
[New Thread 0x7ffff57fe700 (LWP 50243)]
[New Thread 0x7ffff47ff700 (LWP 50244)]
[New Thread 0x7ffff3ffe700 (LWP 50245)]
[New Thread 0x7fffb2ffe700 (LWP 50246)]
[New Thread 0x7fffb27fd700 (LWP 50247)]
[New Thread 0x7fffb1ffc700 (LWP 50248)]
[New Thread 0x7fffb0800700 (LWP 50249)]
[50238] 06-19 11:11:15,045 INFO Server started, Ardb version 0.8.6
[50238] 06-19 11:11:15,045 INFO The server is now ready to accept connections on  0.0.0.0:6379
[New Thread 0x7fffafbff700 (LWP 50250)]
[New Thread 0x7fffaebff700 (LWP 50251)]
[50238] 06-19 11:11:35,870 INFO [Slave]Remote master is a Redis 2.8.19 instance, support partial sync:1
[50238] 06-19 11:11:35,879 INFO Send PSYNC b3046ac3f45faa58945ff551ecba35c8a7baf6e2 5079549
[50238] 06-19 11:11:35,887 INFO Recv psync reply:FULLRESYNC 4657a9f731fc2bab7ef9c8d52c342ca97c90c90d 248915
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffafbff700 (LWP 50250)]
0x00007ffff6c01cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff6c01cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff6c050d8 in __GI_abort () at abort.c:89
#2  0x00007ffff750c535 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff750a6d6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff750a703 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff750a922 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff750ae0d in operator new(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff7566209 in std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff7566dcb in std::string::_Rep::_M_clone(std::allocator<char> const&, unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007ffff7566e64 in std::string::reserve(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007ffff75670af in std::string::append(char const*, unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00000000005065d0 in ardb::print_cursor (cursor=0x7fffadcb0800, str=...) at engine/wiredtiger_engine.cpp:640
#12 0x00000000005067dc in ardb::WiredTigerEngine::Stats (this=<optimized out>) at engine/wiredtiger_engine.cpp:669
#13 0x00000000004b138a in ardb::Ardb::FillInfoResponse (this=this@entry=0x7fffffffd5d0, section=..., info=...) at command/server.cpp:208
#14 0x00000000004b2b84 in ardb::Ardb::Info (this=0x7fffffffd5d0, ctx=..., cmd=...) at command/server.cpp:422
#15 0x000000000040ca11 in ardb::Ardb::DoCall (this=this@entry=0x7fffffffd5d0, ctx=..., setting=..., args=...) at ardb.cpp:874
#16 0x000000000040f756 in ardb::Ardb::Call (this=0x7fffffffd5d0, ctx=..., args=..., flags=0) at ardb.cpp:1026
#17 0x000000000043d500 in ardb::RedisRequestHandler::MessageReceived (this=0x7ffff483b1e0, ctx=..., e=...) at network.cpp:66
#18 0x000000000040bb13 in HandleStreamEvent (e=..., ctx=..., this=<optimized out>) at ./common/channel/channel_upstream_handler.hpp:133
#19 ardb::ChannelPipeline::SendUpstream<ardb::codec::RedisCommandFrame> (ctx=<optimized out>, e=..., this=<optimized out>) at ./common/channel/all_includes.hpp:89
#20 0x000000000042690d in SendUpstream<ardb::MessageEvent<ardb::codec::RedisCommandFrame> > (this=<optimized out>, this=<optimized out>, e=...)
    at ./common/channel/all_includes.hpp:164
#21 fire_message_received<ardb::codec::RedisCommandFrame> (destructor=0x0, message=0x7fffafbfec50, ctx=...) at ./common/channel/channel_helper.hpp:91
#22 ardb::codec::StackFrameDecoder<ardb::codec::RedisCommandFrame>::CallDecode (this=0x7ffff6264c10, context=..., channel=0x7ffff6261e40, cumulation=...)
    at ./common/channel/codec/stack_frame_decoder.hpp:102
#23 0x0000000000426e3f in ardb::codec::StackFrameDecoder<ardb::codec::RedisCommandFrame>::MessageReceived (this=0x7ffff6264c10, ctx=..., e=...)
    at ./common/channel/codec/stack_frame_decoder.hpp:157
#24 0x000000000046d013 in HandleStreamEvent (e=..., ctx=..., this=<optimized out>) at ./common/channel/channel_upstream_handler.hpp:133
#25 ardb::ChannelPipeline::SendUpstream<ardb::Buffer> (ctx=<optimized out>, e=..., this=<optimized out>) at ./common/channel/all_includes.hpp:89
#26 0x000000000046e360 in SendUpstream<ardb::MessageEvent<ardb::Buffer> > (event=..., this=0x7ffff6261e78) at ./common/channel/all_includes.hpp:128
#27 fire_message_received<ardb::Buffer> (destructor=0x0, message=0x7ffff6261ea8, channel=0x7ffff6261e40) at ./common/channel/channel_helper.hpp:83
#28 ardb::Channel::OnRead (this=0x7ffff6261e40) at common/channel/channel.cpp:523
#29 0x000000000046ce3d in ardb::Channel::IOEventCallback (eventLoop=<optimized out>, fd=<optimized out>, clientData=0x7ffff6261e40, mask=1)
    at common/channel/channel.cpp:53
#30 0x000000000048b1f0 in aeProcessEvents (eventLoop=eventLoop@entry=0x7ffff6033658, flags=flags@entry=3) at common/channel/redis/ae.c:429
#31 0x000000000048b4db in aeMain (eventLoop=0x7ffff6033658) at common/channel/redis/ae.c:485
#32 0x0000000000461bf0 in ardb::Thread::ThreadFunc (data=0x7ffff6264d60) at common/thread/thread.cpp:38
#33 0x00007ffff7bc4182 in start_thread (arg=0x7fffafbff700) at pthread_create.c:312
#34 0x00007ffff6cc547d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb)

**Comment by pedigree** [comment]
This doesnt happen on a recompiled RocksDB, just WiredTiger

**Comment by yinqiwen** [comment]
rewrite wiredtiger support in 0.9, fixed.
