### ISSUE TITLE
tried to install on ubuntu 14.04 with the errors below...

### ISSUE THREAD

**Issue by hwongcom** [yinqiwen/ardb#184]
command i used
storage_engine=leveldb make

Error

>>>>> Building JEMALLOC
patching file configure.ac
make[1]: *** [/usr/local/src/ardb/src/../deps/jemalloc-3.6.0/lib/libjemalloc.a] Error 127
make[1]: Leaving directory `/usr/local/src/ardb/src'
make: *** [all] Error 2

I've done apt-get install build-essential and also apt-get install libjemalloc-dev

any ideas why it doesnt work?

**Comment by yinqiwen** [comment]
check your env if `autoconf` or `patch` installed.

**Comment by hwongcom** [comment]
thanks. apt-get install patch solved it.
