### ISSUE TITLE
关于<<一种基于Redis/Ardb的混合部署存储方案>>

### ISSUE THREAD

**Issue by IceiceFire** [yinqiwen/ardb#186]
看了您的<<一种基于Redis/Ardb的混合部署存储方案>>文章, 我做了一下部署, redis主,ardb从
如果redis-master宕掉了,数据清空后master重起,
从起后自动同步,所以ardb-slave数据也清空了, 
ardb里的数据如果很大,即使从启前备分了,也不是好注意.
那么master重起后,能否给个保留ardb数据做法呢?

**Comment by yinqiwen** [comment]
试试修改这个配置
# Slave clear current data store before full resync to master. 
# It make sure that slave keep consistent with master's data. But slave may cost a 
# long time to delete data, it depends on 
# If set by no, then slave may have different data with master.
slave-cleardb-before-fullresync    yes

**Comment by IceiceFire** [comment]
slave-cleardb-before-fullresync yes

这个配置在 你的文章里也读到过,试验了下,master重起,slave的数据仍然和master同步, slave原数据被冲掉了

**Comment by yinqiwen** [comment]
fixed in last commit https://github.com/yinqiwen/ardb/commit/c6e51e323d66cbf3115252a46a26a296a1ddb1f6

**Comment by IceiceFire** [comment]
config.cpp文件下最新：
     conf_get_bool(props, "slave-cleardb-before-fullresync", slave_cleardb_before_fullresync);

从新make

主-从：
redis-master:127.0.0.1:26379
ardb-slave:    127.0.0.1:16379

操作：
-------------------------------------------------------------------------------------------------------------------
主
[root@localhost ~]# /home/cloud/redis/src/redis-server /home/cloud/redis/work/26379.conf
[root@localhost ~]# /home/cloud/redis/src/redis-cli -p 26379
127.0.0.1:26379> keys *
(empty list or set)
-------------------------------------------------------------------------------------------------------------------
从
[root@localhost work]# /usr/local/ardb/src/ardb-server /usr/local/ardb/work/ardb.conf
[root@localhost work]# /home/cloud/redis/src/redis-cli -p 16379
127.0.0.1:16379> keys *
(empty list or set)
127.0.0.1:16379> slaveof 127.0.0.1 26379
OK
127.0.0.1:16379> config set slave-ignore-expire yes
OK
127.0.0.1:16379> config set slave-ignore-del yes
OK
127.0.0.1:16379> config get slave-cleardb-before-fullresync
1) "slave-cleardb-before-fullresync"
2) "yes"
-------------------------------------------------------------------------------------------------------------------
主
127.0.0.1:26379> set 1 aaaaaa
OK
127.0.0.1:26379> set 2 bbbbb
OK
127.0.0.1:26379> set 3 ccccc
OK
127.0.0.1:26379> keys *
1) "3"
2) "1"
3) "2"
127.0.0.1:26379> del 1
(integer) 1
127.0.0.1:26379> del 2
(integer) 1
127.0.0.1:26379> del 3
(integer) 1
127.0.0.1:26379> keys *
(empty list or set)
127.0.0.1:26379> shutdown
-------------------------------------------------------------------------------------------------------------------
从
127.0.0.1:16379> keys *
1) "1"
2) "2"
3) "3"
-------------------------------------------------------------------------------------------------------------------
主
not connected> quit
[root@localhost ~]# /home/cloud/redis/src/redis-server /home/cloud/redis/work/26379.conf
[root@localhost ~]# /home/cloud/redis/src/redis-cli -p 26379127.0.0.1:26379> keys *
(empty list or set)
-------------------------------------------------------------------------------------------------------------------
从
127.0.0.1:16379> keys *
(empty list or set)
-------------------------------------------------------------------------------------------------------------------

slave 的数据仍然被掉了数据，还请帮看一下，因为过两天我想加到生产环境中。

@yinqiwen 拜托

**Comment by yinqiwen** [comment]
slave-cleardb-before-fullresync 改成no

**Comment by IceiceFire** [comment]
OK~ 试验成功，下部测试3天看看情况!
@yinqiwen 谢谢了！：）
