### ISSUE TITLE
Import 在线导入备份数据

### ISSUE THREAD

**Issue by IceiceFire** [yinqiwen/ardb#187]
ardb 新增功能:
Import， 在线导入备份数据，支持Redis Dump以及Ardb Dump

能否说一下市如何操作,使用哪些相关命令?

**Comment by yinqiwen** [comment]
https://github.com/yinqiwen/ardb/wiki/Backup-Commands

**Comment by IceiceFire** [comment]
我用redis客户端作为ardb的使用，版本是2.8.9 应该没有 Import 命令

127.0.0.1:16379> import
(error) ERR Import error
-----------------------------------------------
请问 下面使用的的客户端是什么
redis> import
-------------------------------------------------

@yinqiwen help

**Comment by yinqiwen** [comment]
wiki里有说明，不带参数是按默认路径执行的
