### ISSUE TITLE
tried make with latest ardb but error message below. pls help. thanks

### ISSUE THREAD

**Issue by hwongcom** [yinqiwen/ardb#188]
root@8d1ea3b446cb:/usr/local/src/ardb# storage_engine=leveldb make
cd src && make all
make[1]: Entering directory `/usr/local/src/ardb/src'
echo ">>>>> Building JEMALLOC" && \
	cd /usr/local/src/ardb/src/../deps && \
	tar jxf /usr/local/src/ardb/src/../deps/jemalloc-3.6.0.tar.bz2 && \
	cd /usr/local/src/ardb/src/../deps/jemalloc-3.6.0 && \
	patch < ../../jemalloc.patch && \
	autoconf configure.ac > configure 2> autoconf.out && \
	./configure    > configure.out && \
	make build_lib_static && \
	echo "<<<<< Done building JEMALLOC"
>>>>> Building JEMALLOC
patching file configure.ac
make[1]: *** [/usr/local/src/ardb/src/../deps/jemalloc-3.6.0/lib/libjemalloc.a] Error 127
make[1]: Leaving directory `/usr/local/src/ardb/src'
make: *** [all] Error 2

**Comment by yinqiwen** [comment]
duplicated issue https://github.com/yinqiwen/ardb/issues/184
