### ISSUE TITLE
Unable to restart ardb

### ISSUE THREAD

**Issue by hwongcom** [yinqiwen/ardb#189]
Unable to restart ardb... it was working for the past few weeks.

How can i debug? is there a startup error log file? how do i declare it?

**Comment by hwongcom** [comment]
Any feedback on this one? Please help

**Comment by yinqiwen** [comment]
any log?

**Comment by hwongcom** [comment]
i enabled 
                logfile log/cache.log
which doenst display anything and is not created. the rest of the ardb instances work. i think the db crashed. the problem is.. it creates a pid file and then doesnt do anything anymore, the pid file is left there. 
there is no ardb process. it doesnt create the .sock file to listen to as well. 
i have no idea how to do anything anymore.

**Comment by yinqiwen** [comment]
u can set logfile to stdout and set dameon to false to see the output.

**Comment by hwongcom** [comment]
because it was non crucial, i managed to solve it... the problem is...
[31053] 08-04 14:19:28,814 ERROR Failed to init engine:IO error: /usr/local/ardb-server/data_db/data-stp-2001/LevelDB/MANIFEST-000283: No such file or directory

the last MANIFEST file was 000289... I dont know why it skipped? what's the problem and how to prevent this from happening in future?
