### ISSUE TITLE
错误：‘_mm_crc32_u64’在此作用域中尚未声明

### ISSUE THREAD

**Issue by maoxianfly** [yinqiwen/ardb#192]
CC       util/comparator.o
  CC       util/crc32c.o
util/crc32c.cc: 在函数‘void rocksdb::crc32c::Fast_CRC32(uint64_t*, const uint8_t**)’中:
util/crc32c.cc:318:39: 错误：‘_mm_crc32_u64’在此作用域中尚未声明
   *l = _mm_crc32_u64(*l, LE_LOAD64(*p));
                                       ^
make[2]: *** [util/crc32c.o] 错误 1
make[2]: Leaving directory `/data/usr/local/ardb/deps/rocksdb-3.10'
make[1]: *** [/data/usr/local/ardb/src/../deps/rocksdb-3.10/librocksdb.a] 错误 2
make[1]: Leaving directory `/data/usr/local/ardb/src'
make: *** [all] 错误 2

**Comment by yinqiwen** [comment]
rocksdb need 4.7 or higher version g++.

**Comment by maoxianfly** [comment]
[root@localhost ardb]# g++ -v
使用内建 specs。
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/i686-pc-linux-gnu/5.2.0/lto-wrapper
目标：i686-pc-linux-gnu
配置为：../gcc-5.2.0/configure --enable-checking=release --enable-languages=c,c++ --disable-multilib
线程模型：posix
gcc 版本 5.2.0 (GCC)

**Comment by yinqiwen** [comment]
can u compile rocksdb by it's makefile not from ardb?

**Comment by maoxianfly** [comment]
separate install rocksdb-3.10.2 : 

 CC       util/crc32c.o
util/crc32c.cc: 在函数‘void rocksdb::crc32c::Fast_CRC32(uint64_t*, const uint8_t**)’中:
util/crc32c.cc:318:39: 错误：‘_mm_crc32_u64’在此作用域中尚未声明
   *l = _mm_crc32_u64(*l, LE_LOAD64(*p));
                                       ^
make: *** [util/crc32c.o] 错误 1

**Comment by yinqiwen** [comment]
the code is inside SSE42 macros, is there '-msse4.2' compile flags set in rocksdb's makefile?

**Comment by maoxianfly** [comment]
rocksdb's makefile 文件里没有  '-msse4.2'

**Comment by maoxianfly** [comment]
怎么加？
CFLAGS += -msse4.2
CXXFLAGS += -msse4.2
这样？

**Comment by maoxianfly** [comment]
cd src && make all
make[1]: Entering directory `/data/usr/local/ardb/src'
g++ -o ardb-test engine/rocksdb_engine.o         ../test/test_suite.o ardb.o codec.o comparator.o config.o cron.o logger.o iterator.o network.o options.o statistics.o cache/cache.o  common/util/config_helper.o  common/util/datagram_packet.o  common/util/file_helper.o  common/util/math_helper.o  common/util/mmap.o  common/util/network_helper.o  common/util/redis_helper.o  common/util/socket_address.o  common/util/string_helper.o  common/util/system_helper.o  common/util/time_helper.o  common/util/exception/api_exception.o  common/thread/event_condition.o  common/thread/thread.o  common/buffer/buffer.o  common/buffer/buffer_helper.o  common/geo/geohash_helper.o  common/util/rand.o  common/util/sds.o  common/util/sha1.o  common/redis/crc64.o  common/redis/endianconv.o  common/redis/intset.o  common/redis/lzf_c.o  common/redis/lzf_d.o  common/redis/ziplist.o  common/redis/zipmap.o  common/geo/geohash.o  common/channel/channel.o  common/channel/channel_handler_context.o  common/channel/channel_helper.o  common/channel/channel_pipeline.o  common/channel/channel_service.o  common/channel/socket/clientsocket_channel.o  common/channel/socket/datagram_channel.o  common/channel/socket/serversocket_channel.o  common/channel/socket/socket_channel.o  common/channel/fifo/fifo_channel.o  common/channel/codec/delimiter_frame_decoder.o  common/channel/codec/int_header_frame_decoder.o  common/channel/codec/redis_command_codec.o  common/channel/codec/redis_reply_codec.o  common/channel/codec/redis_reply.o  common/channel/timer/timer_channel.o  common/channel/timer/timer.o  common/channel/timer/timer_task_queue.o  common/channel/signal/signal_channel.o  common/channel/signal/soft_signal_channel.o  common/channel/redis/ae.o  common/channel/redis/zmalloc.o  command/connection.o  command/geo.o  command/hyperloglog.o  command/keys.o  command/lua_scripting.o  command/pubsub.o  command/server.o  command/slowlog.o  command/sort.o  command/t_bitset.o  command/t_hash.o  command/t_list.o  command/transaction.o  command/t_set.o  command/t_string.o  command/t_zset.o  replication/backup.o  replication/master.o  replication/rdb.o  replication/repl_backlog.o  replication/slave.o  /data/usr/local/ardb/src/../deps/rocksdb-3.10/librocksdb.a /data/usr/local/ardb/src/../deps/snappy-1.1.2/.libs/libsnappy.a /data/usr/local/ardb/src/../deps/lua/src/liblua.a /data/usr/local/ardb/src/../deps/jemalloc-3.6.0/lib/libjemalloc.a /data/usr/local/ardb/src/../deps/snappy-1.1.2/.libs/libsnappy.a -lpthread -lz -lbz2 -lrt 
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
make[1]: *** [test] Error 1
make[1]: Leaving directory `/data/usr/local/ardb/src'
make: *** [all] Error 2

**Comment by yinqiwen** [comment]
there is no zlib installed in the host os

**Comment by maoxianfly** [comment]
centos 6.5 64bit
g++ 4.8.5

# yum install zlib
Loaded plugins: security
Setting up Install Process
Package zlib-1.2.3-29.el6.x86_64 already installed and latest version
Nothing to do

有安装的

**Comment by maoxianfly** [comment]
/usr/bin/ld: cannot find -lbz2
collect2: error: ld returned 1 exit status
make[1]: *** [test] Error 1
make[1]: Leaving directory `/data/usr/local/ardb/src'
make: *** [all] Error 2

lbz2 又是什么库？

**Comment by yinqiwen** [comment]
bzip2

**Comment by maoxianfly** [comment]
没问题了， 终于已编译，谢谢。
