### ISSUE TITLE
make on mac os x 10.10.3

### ISSUE THREAD

**Issue by millawell** [yinqiwen/ardb#193]
I had some troubles to run the make file on my machine:

    $ machine
    x86_64h
    $ arch
    i386
    $ gcc --version
    gcc (Homebrew gcc47 4.7.4 --with-all-languages) 4.7.4
    Copyright (C) 2012 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

The error messages were:

    Building ROCKSDB
      CC       db/c.o
    /var/folders/hr/qpmhq7sj76x2kyvqw8qc1l000000gn/T//ccHGeibZ.s:4947:no such instruction: `shlx %rax, %r10,%rsi'
    /var/folders/hr/qpmhq7sj76x2kyvqw8qc1l000000gn/T//ccHGeibZ.s:5048:no such instruction: `shlx %rax, %r9,%rdi'
    /var/folders/hr/qpmhq7sj76x2kyvqw8qc1l000000gn/T//ccHGeibZ.s:5181:no such instruction: `shlx %rax, %r8,%rdi'
    /var/folders/hr/qpmhq7sj76x2kyvqw8qc1l000000gn/T//ccHGeibZ.s:8659:no such instruction: `vmovsd 240(%rsi), %xmm0'
    /var/folders/hr/qpmhq7sj76x2kyvqw8qc1l000000gn/T//ccHGeibZ.s:8731:no such instruction: `vmovsd %xmm0, 240(%rdi)'
    /var/folders/hr/qpmhq7sj76x2kyvqw8qc1l000000gn/T//ccHGeibZ.s:8734:no such instruction: `vmovsd 248(%rsi), %xmm0'
    /var/folders/hr/qpmhq7sj76x2kyvqw8qc1l000000gn/T//ccHGeibZ.s:8740:no such instruction: `vmovsd %xmm0, 248(%rdi)'
    /var/folders/hr/qpmhq7sj76x2kyvqw8qc1l000000gn/T//ccHGeibZ.s:16719:no such instruction: `vmovsd LC4(%rip), %xmm0'
    /var/folders/hr/qpmhq7sj76x2kyvqw8qc1l000000gn/T//ccHGeibZ.s:16723:no such instruction: `vmovsd %xmm0, (%rax)'
    /var/folders/hr/qpmhq7sj76x2kyvqw8qc1l000000gn/T//ccHGeibZ.s:16749:no such instruction: `vmovsd %xmm0, (%rdi)'
    /var/folders/hr/qpmhq7sj76x2kyvqw8qc1l000000gn/T//ccHGeibZ.s:19691:no such instruction: `vmovsd %xmm0, 496(%rdi)'
    /var/folders/hr/qpmhq7sj76x2kyvqw8qc1l000000gn/T//ccHGeibZ.s:19701:no such instruction: `vmovsd %xmm0, 504(%rdi)'
    /var/folders/hr/qpmhq7sj76x2kyvqw8qc1l000000gn/T//ccHGeibZ.s:20787:no such instruction: `vmovsd %xmm0, -56(%rbp)'
    /var/folders/hr/qpmhq7sj76x2kyvqw8qc1l000000gn/T//ccHGeibZ.s:30570:no such instruction: `shlx %rcx, %r10,%r8'
    /var/folders/hr/qpmhq7sj76x2kyvqw8qc1l000000gn/T//ccHGeibZ.s:30584:no such instruction: `shlx %rsi, %r10,%r9'
    /var/folders/hr/qpmhq7sj76x2kyvqw8qc1l000000gn/T//ccHGeibZ.s:30892:no such instruction: `shlx %r9, %rcx,%rsi'
    /var/folders/hr/qpmhq7sj76x2kyvqw8qc1l000000gn/T//ccHGeibZ.s:30904:no such instruction: `shlx %r8, %rcx,%r10'
    /var/folders/hr/qpmhq7sj76x2kyvqw8qc1l000000gn/T//ccHGeibZ.s:31112:no such instruction: `shlx %r15, %rcx,%rsi'
    /var/folders/hr/qpmhq7sj76x2kyvqw8qc1l000000gn/T//ccHGeibZ.s:31126:no such instruction: `shlx %r13, %rcx,%rax'
    /var/folders/hr/qpmhq7sj76x2kyvqw8qc1l000000gn/T//ccHGeibZ.s:32598:no such instruction: `andn (%rcx), %rdx,%rax'
    /var/folders/hr/qpmhq7sj76x2kyvqw8qc1l000000gn/T//ccHGeibZ.s:32648:no such instruction: `shlx %rdx, %rsi,%rdx'
    /var/folders/hr/qpmhq7sj76x2kyvqw8qc1l000000gn/T//ccHGeibZ.s:34341:no such instruction: `vmovsd 232(%r9,%r10), %xmm0'
    /var/folders/hr/qpmhq7sj76x2kyvqw8qc1l000000gn/T//ccHGeibZ.s:34342:no such instruction: `vmovsd %xmm0, 232(%r8,%r11)'
    /var/folders/hr/qpmhq7sj76x2kyvqw8qc1l000000gn/T//ccHGeibZ.s:34343:no such instruction: `vmovsd 240(%r9,%r10), %xmm0'
    /var/folders/hr/qpmhq7sj76x2kyvqw8qc1l000000gn/T//ccHGeibZ.s:34344:no such instruction: `vmovsd %xmm0, 240(%r8,%r11)'
    /var/folders/hr/qpmhq7sj76x2kyvqw8qc1l000000gn/T//ccHGeibZ.s:35495:no such instruction: `vmovsd -768(%rbp), %xmm0'
    /var/folders/hr/qpmhq7sj76x2kyvqw8qc1l000000gn/T//ccHGeibZ.s:35525:no such instruction: `vmovsd %xmm0, -280(%rbp)'
    /var/folders/hr/qpmhq7sj76x2kyvqw8qc1l000000gn/T//ccHGeibZ.s:35528:no such instruction: `vmovsd -760(%rbp), %xmm0'
    /var/folders/hr/qpmhq7sj76x2kyvqw8qc1l000000gn/T//ccHGeibZ.s:35560:no such instruction: `vmovsd %xmm0, -272(%rbp)'
    /var/folders/hr/qpmhq7sj76x2kyvqw8qc1l000000gn/T//ccHGeibZ.s:39065:no such instruction: `vmovsd -768(%rbp), %xmm0'
    /var/folders/hr/qpmhq7sj76x2kyvqw8qc1l000000gn/T//ccHGeibZ.s:39095:no such instruction: `vmovsd %xmm0, -280(%rbp)'
    /var/folders/hr/qpmhq7sj76x2kyvqw8qc1l000000gn/T//ccHGeibZ.s:39098:no such instruction: `vmovsd -760(%rbp), %xmm0'
    /var/folders/hr/qpmhq7sj76x2kyvqw8qc1l000000gn/T//ccHGeibZ.s:39130:no such instruction: `vmovsd %xmm0, -272(%rbp)'
    make[2]: *** [db/c.o] Error 1
    

as well as:

    ld: library not found for -lrt
    collect2: error: ld returned 1 exit status

I had to apply the following changes to the `src/Makefile`:

    @@ -182 +182 @@ ifeq ($(storage_engine), rocksdb)
    -  LIBS:= ${ROCKSDB_LIBA} ${SNAPPY_LIBA} ${LIBS} -lz -lbz2 -lrt
    +  LIBS:= ${ROCKSDB_LIBA} ${SNAPPY_LIBA} ${LIBS} -lz -lbz2
    @@ -190 +190 @@ ifeq ($(storage_engine), wiredtiger)
    -  LIBS:= ${WIREDTIGER_LIBA} ${SNAPPY_LIBA} ${LIBS} -lrt -ldl
    +  LIBS:= ${WIREDTIGER_LIBA} ${SNAPPY_LIBA} ${LIBS} -ldl
    
    @@ -290 +290 @@ $(ROCKSDB_LIBA): $(SNAPPY_LIBA) $(ROCKSDB_PATH)
    -       CXXFLAGS="-I${SNAPPY_PATH} -O2 -DNDEBUG" CFLAGS="-I${SNAPPY_PATH}" LDFLAGS="${SNAPPY_PATH}/.libs" $(MAKE) librocksdb.a && \
    +       CXXFLAGS="-I${SNAPPY_PATH} -O2 -DNDEBUG" CFLAGS="-march=native -Wa,-q -I${SNAPPY_PATH}" LDFLAGS="${SNAPPY_PATH}/.libs" $(MAKE) librocksdb.a && \

hope it helps improving the *out of the box* behavior

**Comment by yinqiwen** [comment]
fixed in 0.9
