### ISSUE TITLE
inefficient hset

### ISSUE THREAD

**Issue by CoderDeathEyE** [yinqiwen/ardb#194]
I found it can only get 3000 qps with hset, event sdd employed, and disk io is far to reach the bottleneck
I wonder if there is some wrong with hset procedure

This is my test infomation:
engine: rocksdb.3.10
benchmark: redigo
item average: 4k
concurrency: 20

configuration:
rocksdb.statistics_enable      yes
rocksdb.max_open_files         100000
#if 'use_bulk_load_options' set to 'yes', all other rocksdb's options below would be ignored 
rocksdb.use_bulk_load_options  no
rocksdb.block_cache_size       512m
rocksdb.block_size             0
rocksdb.write_buffer_size      64m
rocksdb.block_restart_interval 0
rocksdb.bloom_bits             10
rocksdb.batch_commit_watermark 1024
# Specify the rocksdb compression
# This can be one of snappy/none
rocksdb.compression            none
rocksdb.skip_log_error_on_recovery yes
#0 means no limit
rocksdb.flush_compact_rate_bytes_per_sec  0
rocksdb.hard_rate_limit        2.0
rocksdb.disableWAL             no
rocksdb.max_manifest_file_size 2G

**Comment by yinqiwen** [comment]
For 'hset' operations, ardb would query the key's info(to forbid 'hset' non hash key), this means there is at least one read and one write ops for each 'hset'.

**Comment by deatheyes** [comment]
Thanks. 
This will become a bottleneck as the data set grows.Maybe it can make some tradeoff between write efficiency and strict rules so as to get the benefit from LSM tree.

**Comment by gaurav4556** [comment]
can we improve "hset" operation performance? We are using hset operation very heavily in our application.

**Comment by yinqiwen** [comment]
currently, i'm rewrite ardb in my spare time, which would use many rocksdb's new features.

The rocksdb's  [merge](https://github.com/facebook/rocksdb/wiki/Merge-Operator) operator could improve performance of read-modify-write operations.

**Comment by gaurav4556** [comment]
@yinqiwen  Thanks, Actually we are planning to use ardb as main database in our Application. So I am evaluating ARDB. Can we use it for Production application?

**Comment by yinqiwen** [comment]
Ardb is not well tested in many scenarios, we are only use it to store our geo data as a spartial db in the production env, it's still unstable IMO.
