### ISSUE TITLE
Invalid argument(s)

### ISSUE THREAD

**Issue by maoxianfly** [yinqiwen/ardb#195]
127.0.0.1:16379> set aaa [{"a":79496554}]
Invalid argument(s)

**Comment by maoxianfly** [comment]
set mapfbbosspet_DRFBMOVE_5_135_15 hehehhe
sleep 3 s
get mapfbbosspet_DRFBMOVE_5_135_15 
 --> nil

**Comment by yinqiwen** [comment]
fixed i 0.9
