### ISSUE TITLE
Ardb with LMDB crashing after startup

### ISSUE THREAD

**Issue by gonzajg** [yinqiwen/ardb#200]
Hi, 

We finished loading a big RDB file (37GB) to ardb with lmdb database. The loading part was OK but after ending ardb crashes. We start it up, it works for some minutes while continously increasing memory usage and almost no commands ran against it until it crashes again. 

My guess is that it's running out of memory. There's nothing in the logs (DEBUG level).

We are running ardb master in a centos 6 ec2 amazon server. 

We've seen that there are 3 configuration parameters but none seem to be related to max memory usage.

#lmdb's options 
lmdb.database_max_size         200G
lmdb.readahead                 yes
lmdb.batch_commit_watermark    4096

**Comment by yinqiwen** [comment]
it seems lmdb related bug since ardb do nothing after reopen lmdb.

And lmdb in ardb is upgraded to 0.9.18 which fixed many bugs since 0.9.10 may resolve this bug.
