### ISSUE TITLE
please let ardb work with multi slave mode, support redis cluster 

### ISSUE THREAD

**Issue by laochen** [yinqiwen/ardb#203]
I want all redis cluster nodes's data pull in one ardb with multi slave mode, it's good idea, why not?

steps:
1. change ardb.conf, support multi-line slaveof
slaveof 127.0.0.1:7000
slaveof 127.0.0.1:7010
slaveof 127.0.0.1:7020
slaveof 127.0.0.1:7030
2.  modify server.cpp, ardb.cpp , ardb.hpp file 
modify variable m_slave,master_host   and modify some code

how about?

**Comment by yinqiwen** [comment]
It's hard to implement  this feature with multi slave/replication instances in ardb, which would break backward compatibility.
And i doubt that it would work well  in reality since ardb is much slower than redis, ardb can NOT handle  too many write operations synced from redis.

**Comment by laochen** [comment]
ok, thanks. have any tools for migrate all cluster nodes's data ?  not realtime
