### ISSUE TITLE
keyscount * returns 0

### ISSUE THREAD

**Issue by gokceneraslan** [yinqiwen/ardb#218]
I'm using the LMDB backend and have millions of keys. I can see the keys when I run `redis-cli -p 16379 keys "*" limit 10`, But for some reason `keyscount "*"` returns `(integer) 0`. `database_max_size` is `72GB` and size of `data/LMDB/data.mdb` is 27GB when I check with `du`. I use the `ardb.conf` file as configuration file.

**Comment by luweijie007** [comment]
@yinqiwen , I see this problem too, can fix it?

**Comment by yinqiwen** [comment]
it's a bug that `option's limit` is -1 or this situation.
https://github.com/yinqiwen/ardb/blob/master/src/command/keys.cpp#L236

**Comment by yinqiwen** [comment]
fixed in 0.9
