### ISSUE TITLE
Slow sintercount

### ISSUE THREAD

**Issue by refaelos** [yinqiwen/ardb#220]
Hey,

Just started using ardb and I found out that `sintercount` is extremely slow. On 2 sets of ~3M items each, it takes around 30 seconds to complete.

Is that the expected behavior?

(my storage engine is leveldb)

**Comment by yinqiwen** [comment]
The complexity is 2*O(N) + O(logn) on disk, it would be pretty slow if the N is huge.

**Comment by refaelos** [comment]
@yinqiwen so you're saying it's the wrong db for this operation or there's an option to improve that?
