### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by lixiaominggit** [yinqiwen/ardb#221]
![image](https://cloud.githubusercontent.com/assets/5425397/13517950/d12a8598-e203-11e5-9753-d85c3426e03b.png)
能给出指导吗

之前的编译是可以通过的！！！

**Comment by yinqiwen** [comment]
完整的错误是什么？

**Comment by lixiaominggit** [comment]
好多错误
![image](https://cloud.githubusercontent.com/assets/5425397/13559879/cffacf78-e453-11e5-8dd3-86c845a7c3f6.png)
![image](https://cloud.githubusercontent.com/assets/5425397/13559897/f15bd77a-e453-11e5-9ccd-ba452d72c89d.png)
![image](https://cloud.githubusercontent.com/assets/5425397/13559905/0a943160-e454-11e5-978f-c7c203b654bd.png)
![image](https://cloud.githubusercontent.com/assets/5425397/13559909/178fa48a-e454-11e5-9abf-d4a0b778ddd4.png)
我只是个php，对你们的错误信息不了解，还希望您能多帮我看看什么原因，记得第一次安装的时候当时是因为gcc版本低，我升级gcc后好了，但是最近下载新版本编译的时候错误太多了

**Comment by yinqiwen** [comment]
错误都是c++11的特性，需要高版本的g++以及-std=c++11 编译参数
你这个g++应该版本足够了，可能是rocksdb的makefile里没有-std=c++11参数

**Comment by lixiaominggit** [comment]
编译通过了，谢谢哈
