### ISSUE TITLE
KEYS pattern [LIMIT num] [FROM start] can not right

### ISSUE THREAD

**Issue by luweijie007** [yinqiwen/ardb#224]
I use 
ardb_version:0.8.6
engine:RocksDB

and:
127.0.0.1:16479> keys 
1) "12"
2) "12A"
3) "13"
4) "14"
5) "a"
6) "key
 but this command:
127.0.0.1:16479> keys * from "12" limit 3
(error) ERR Syntax error, try KEYS 
or
127.0.0.1:16479> keys * from 12 limit 3
(error) ERR Syntax error, try KEYS

How can I use this command "keys * limit" ?
Thankful

**Comment by yinqiwen** [comment]
use standard redis command 'scan 0 match "12*" count 10'  instead, the '[LIMIT num] [FROM start]' is removed from 'keys' command in v0.9
