### ISSUE TITLE
Ardb running at 100% all the time. Is this normal?

### ISSUE THREAD

**Issue by hwongcom** [yinqiwen/ardb#226]
Ardb running at 100% all the time after 4 days. Is this normal?
Previously starting, it only uses 40% cpu max. now it's like 100%.

How do I know why it's running >100% all the time?
Though I'm really using it as a primary cache.

Any hints?

**Comment by yinqiwen** [comment]
It maybe there is some background compact task working wich cost too much cpu. u can use gdb o attach the running process to get the running stack trace of all threads, which would give more detais about it.
