### ISSUE TITLE
Does TTL work real-timely ?

### ISSUE THREAD

**Issue by wuyingfengsui** [yinqiwen/ardb#227]
When a key expires, would it be removed immediately, or ardb doing this until it be scaned ?

**Comment by yinqiwen** [comment]
it would be deleted while it be scaned. It's too expensive to remove expired key immediately.

**Comment by wuyingfengsui** [comment]
Does it have a background process to do this periodically ?

**Comment by yinqiwen** [comment]
There is a background thread  to do this work, but it's only work well if only a few keys were setting expired time. If all keys have expire time,  the thread would be very slow to do this work.

in 'rocksdb-only' branch, i'm using rocksdb's compaction filter to do this work, the expired keys would only be deleted in compaction job.

**Comment by wuyingfengsui** [comment]
Thanks.
