### ISSUE TITLE
Build failed with branch rocksdb-only?

### ISSUE THREAD

**Issue by wikimore** [yinqiwen/ardb#228]
I make it on my mac and failed.

error is 

>  Building sparsehash
> tar: Error opening archive: Failed to open '/Users/nali/dev/ardb/src/../deps/sparsehash-sparsehash-2.0.3.tar.gz'
> /bin/sh: line 0: cd: /Users/nali/dev/ardb/src/../deps/sparsehash-sparsehash-2.0.3: No such file or directory
> /bin/sh: ./configure: No such file or directory
> make[2]: *** No rule to make target `src/sparsehash/internal/sparseconfig.h'.  Stop.
> make[1]: *** [/Users/nali/dev/ardb/src/../deps/sparsehash-sparsehash-2.0.3/src/config.h] Error 2
> make: *** [all] Error 2

There is no file named sparsehash-sparsehash-2.0.3 in deps folder.

**Comment by yinqiwen** [comment]
u can download it  at https://github.com/sparsehash/sparsehash/releases

**Comment by wikimore** [comment]
@yinqiwen rocksdb-4.3.1.tar.gz not found.

**Comment by wikimore** [comment]
@yinqiwen  i can download it at https://github.com/facebook/rocksdb/releases/tag/v4.3.1

**Comment by wikimore** [comment]
but, can u push them to them repository?

**Comment by yinqiwen** [comment]
this branch is still in developing, all dependency would be ready when it's stable enough .
