### ISSUE TITLE
rpop return nil

### ISSUE THREAD

**Issue by vlike** [yinqiwen/ardb#231]
127.0.0.1:3722>
127.0.0.1:3722> llen testlist
(integer) 9121
127.0.0.1:3722>
127.0.0.1:3722>
**127.0.0.1:3722> rpop testlist
(nil)**
127.0.0.1:3722>
127.0.0.1:3722>
127.0.0.1:3722> lpop testlist
"123456"
127.0.0.1:3722>

# Server
ardb_version:0.8.6
ardb_home:/data/USB/data/db/ardb
engine:LevelDB

**Comment by vlike** [comment]
在频繁 push,pop的场景下，此问题频繁发生

**Comment by yinqiwen** [comment]
it's seems a bug related 'max_index' in list meta.
currently, i'm working in branch 'rocksdb-only', this bug would only be fixed in 'rocksdb-only'.

**Comment by yinqiwen** [comment]
now we have simpler list implementition in v0.9, it should fixed this.
