### ISSUE TITLE
rename-command in ardb.conf

### ISSUE THREAD

**Issue by limbo127** [yinqiwen/ardb#234]
How work rename-command in ardb.conf
rename-command CONFIG ""    works

but 
multiple rename-command does not work
rename-command CONFIG ""
rename-command GET ""

=> Invalid 'rename-command' config 

Regards, 
Nicolas

**Comment by limbo127** [comment]
in fact, the second parameter seems to be different
rename-command CONFIG "a"
rename-command GET "b"
works 
rename-command CONFIG "a"
rename-command GET "a"
not , this is "normal" behaviour, but
how disable command, "" does not work multiple time

**Comment by yinqiwen** [comment]
are u using latest code at brach 0.9?  There is a bug that server try to rename commands before parsing the config,  but no such bug that 'Invalid 'rename-command' config' with multiple rename-command.

**Comment by yinqiwen** [comment]
And the bug mentioned  is fixed in last commit.

**Comment by limbo127** [comment]
no, i'm using 0.8.7
Regards

**Comment by yinqiwen** [comment]
fixed in brach 0.8
