### ISSUE TITLE
Anyone employ ardb in production environment

### ISSUE THREAD

**Issue by supershy** [yinqiwen/ardb#242]
We're evaluating between ardb and qika for our priority queue solution. But it seems not stable enough including v0.8.1 & 0.9. Memory footprint seems always incrementing. And the ops degrades after running the server for one day or two.

**Comment by yinqiwen** [comment]
Any details about memory footprint?

And about ops degredes, since all kv backend use tree like data structure, more data saved, more slow to query data if cache missing.
