### ISSUE TITLE
qiying, help me!

### ISSUE THREAD

**Issue by junneyang** [yinqiwen/ardb#245]
redis-server端有很多链接没有断开，一直是ESTAB状态，显示客户端连接着
但是客户端netstat看没有连接
服务端：
![qq 20160525173907](https://cloud.githubusercontent.com/assets/6802322/15535365/9f0c3c00-229f-11e6-86c5-0e0cca446a4e.png)

客户端：
![qq 20160525173911](https://cloud.githubusercontent.com/assets/6802322/15535368/a48c938c-229f-11e6-8828-9083e64499a1.png)

这个可能是什么原因？
thanks !

**Comment by yinqiwen** [comment]
网络闪断会导致这个问题。 你可以自己启动一个server， 另外一台机器连上这个server，然后拔掉一边的网线重现

**Comment by junneyang** [comment]
应该是这个问题，网络闪断。
把 redis配置里面的keepalive设置了一下就OK了。
