### ISSUE TITLE
I migrated my db data from a server to the other, but now it fails to start.

### ISSUE THREAD

**Issue by hwongcom** [yinqiwen/ardb#247]
I migrated my db data from a server to the other, but now it fails to start in the new server. does not throw and error. how do I check the starting log / error log? or how do i force it to report why it fails to start?

**Comment by yinqiwen** [comment]
why u thought it  fails to start? any error log in the output/log?

**Comment by hwongcom** [comment]
i solved the problem but where is the output/error log? it was because i have another process running that is sharing the same filename of the db socket file

**Comment by hwongcom** [comment]
oops, i have another instance but it's also facing the same problem. i have no idea where is the error log. where is it? it doesnt tell me why it doesnt run

**Comment by yinqiwen** [comment]
just check your ardb.conf the `logfile` setting.

**Comment by hwongcom** [comment]
it doesnt show anything and it doesnt run. when i typed the command, the process doesnt spawn and there's nothing in the log.

**Comment by hwongcom** [comment]
it generates a pid file but the process doesnt appear.

**Comment by yinqiwen** [comment]
is your `logfile` stdout?     and no core dump file generated?

**Comment by hwongcom** [comment]
i changed the logfile to an actual file. i have no idea whether it's using the old or new dump file. is it safe to delete the dump file?

**Comment by yinqiwen** [comment]
just remove the data dir if u want to restart with a clean env.  
there is a `data-dir` in ardb.conf
