### ISSUE TITLE
redis crashes when I try to start it with ardb snapshot file

### ISSUE THREAD

**Issue by harutyundermenjyan** [yinqiwen/ardb#248]
It seem we have another issue that is when I am trying to start redis with dump file which previously saved by ardb save command the redis crashes.
here my steps:
1) 127.0.0.1:16379> save
OK
(593.33s) 
2) mv /var/lib/ardb/backup/redis-snapshot.1464335990 /var/lib/redis/dump.rdb
3) service redis-server start     <-----> here the redis crashes
Please see the redis log file output below:
[25127] 27 May 15:52:44.499 # --- CLIENT LIST OUTPUT
[25127] 27 May 15:52:44.499 #
[25127] 27 May 15:52:44.499 # --- REGISTERS
[25127] 27 May 15:52:44.499 #
RAX:0000000000000000 RBX:0000000000473684
RCX:0000000000000005 RDX:0000000000000006
RDI:00007f37d9c06000 RSI:000000000000003c
RBP:0000000000474da5 RSP:00007ffcf56228c0
R8 :00007f37d9c427e0 R9 :00007f37db195780
R10:00007f37da8226a0 R11:0000000000000206
R12:0000000000000405 R13:0000000000000000
R14:0000000000000031 R15:00007f37d9ceb2b0
RIP:000000000044202a EFL:0000000000010202
CSGSFS:0000000000000033
[25127] 27 May 15:52:44.499 # (00007ffcf56228cf) -> 0000000000000031
[25127] 27 May 15:52:44.499 # (00007ffcf56228ce) -> 0000000000000000
[25127] 27 May 15:52:44.499 # (00007ffcf56228cd) -> 00007f37d9c42480
[25127] 27 May 15:52:44.499 # (00007ffcf56228cc) -> 00007f37d9c15980
[25127] 27 May 15:52:44.499 # (00007ffcf56228cb) -> ffffffffffffffff
[25127] 27 May 15:52:44.499 # (00007ffcf56228ca) -> 0000000000000003
[25127] 27 May 15:52:44.499 # (00007ffcf56228c9) -> 000000000042b50a
[25127] 27 May 15:52:44.499 # (00007ffcf56228c8) -> 0000000000000039
[25127] 27 May 15:52:44.499 # (00007ffcf56228c7) -> 00007ffcf5622980
[25127] 27 May 15:52:44.499 # (00007ffcf56228c6) -> 0000000000000039
[25127] 27 May 15:52:44.499 # (00007ffcf56228c5) -> 00000000004247c8
[25127] 27 May 15:52:44.499 # (00007ffcf56228c4) -> 00007f37d9c104c8
[25127] 27 May 15:52:44.499 # (00007ffcf56228c3) -> 000000000042ceea
[25127] 27 May 15:52:44.499 # (00007ffcf56228c2) -> 00007f37d9c42480
[25127] 27 May 15:52:44.499 # (00007ffcf56228c1) -> 0000000000000031
[25127] 27 May 15:52:44.499 # (00007ffcf56228c0) -> 00007ffcf5622980
[25127] 27 May 15:52:44.499 # --- FAST MEMORY TEST
[25127] 27 May 15:52:44.500 # Bio thread for job type #0 terminated
[25127] 27 May 15:52:44.500 # Bio thread for job type #1 terminated
[25127] 27 May 15:52:45.523 # Fast memory test PASSED, however your memory can still be broken. Please run a memory test for several hours if possible.
[25127] 27 May 15:52:45.523 #
=== REDIS BUG REPORT END. Make sure to include from START to END. ===

   Please report the crash opening an issue on github:

       http://github.com/antirez/redis/issues

Suspect RAM error? Use redis-server --test-memory to veryfy it.

**Comment by harutyundermenjyan** [comment]
in case of there is a lot of free mem on the server

**Comment by yinqiwen** [comment]
which version of redis are u using?

**Comment by harutyundermenjyan** [comment]
redis-server v2.8.4-2 on ubuntu 14.04 LTS

**Comment by yinqiwen** [comment]
The generated redis RDB format is 7, which is introduced in redis 3.0 +, can u test with redis 3.2.

**Comment by harutyundermenjyan** [comment]
**here the output of redis-server 3.2.0 latest stable**
31816:M 28 May 13:42:32.287 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
31816:M 28 May 13:42:32.287 # Server started, Redis version 3.2.0
31816:M 28 May 13:42:32.287 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
31816:M 28 May 13:42:33.003 # Corrupt RDB detected at rdb.c:1199 (Unknown object type). Running 'redis-check-rdb dump.rdb'
31816:M 28 May 13:42:33.159 # ==== Processed 2 valid opcodes (in 14643569 bytes) =============================
31816:M 28 May 13:42:33.159 # ==== Error trace (ZSET: similar_images:163649337001202) ========================
31816:M 28 May 13:42:33.159 # 0x00df7bc3 - Followed by invalid type
31816:M 28 May 13:42:33.159 # 0x00df717a - Error for type ZSET
31816:M 28 May 13:42:54.360 # ==== Skipped 33082387 bytes (resuming at 0x02d83d8d) ===========================
31816:M 28 May 13:42:54.360 # ==== Processed 3 valid opcodes (in 319017 bytes) ===============================
31816:M 28 May 13:42:54.360 # ==== Error trace (HASH: .38?photos:187529881000202?0.38?photo...9?H) ===========
31816:M 28 May 13:42:54.360 # 0x02ddd682 - Followed by invalid type
31816:M 28 May 13:42:54.360 # 0x02dd1bb6 - Error for type HASH
31816:M 28 May 13:43:31.788 # ==== Skipped 57295951 bytes (resuming at 0x06476005) ===========================
31816:M 28 May 13:43:31.791 # ==== Processed 3 valid opcodes (in 17351772 bytes) =============================
31816:M 28 May 13:43:31.791 # ==== Error trace (HASH: .37?photos:182854630003202?0.372?phot...9?H) ===========
31816:M 28 May 13:43:31.791 # 0x0750b7f9 - Followed by invalid type
31816:M 28 May 13:43:31.791 # 0x07502461 - Error for type HASH
31816:M 28 May 13:45:18.458 # ==== Skipped 192925559 bytes (resuming at 0x12cff3d8) ==========================
31816:M 28 May 13:45:18.461 # ==== Processed 3 valid opcodes (in 18401752 bytes) =============================
31816:M 28 May 13:45:18.461 # ==== Error trace (ZSET: similar_images:198756135000202) ========================
31816:M 28 May 13:45:18.461 # 0x13e9de99 - Followed by invalid type
31816:M 28 May 13:45:18.461 # 0x13e8bdb0 - Error for type ZSET

**Comment by harutyundermenjyan** [comment]
it crashes again

**Comment by harutyundermenjyan** [comment]
If it convenient for you I can share or send you my db to make it possible for the corresponding future tests to make it yourself In order to facilitate the acceleration of the solution.

**Comment by yinqiwen** [comment]
yes,  if u can upload the rdb to some where i can download, it would be much better.  

and what the output of 'redis-check-rdb dump.rdb' which the crash log suggest?

**Comment by harutyundermenjyan** [comment]
therefore now I cant save it to make a snapshot to share it with you.

**Comment by yinqiwen** [comment]
Is there any error log at the tail of the log when save failed?

**Comment by harutyundermenjyan** [comment]
Anyhow I've not noticed an error.

**Comment by yinqiwen** [comment]
is the key 'similar_images:163649337001202' only have 29 members in ardb while  there is 58 members in redis?

**Comment by yinqiwen** [comment]
I just found the root cause of this issue,  the fix is here https://github.com/yinqiwen/ardb/commit/a0be40570653c88ef009a4af4a7e9211d87377d7

**Comment by yinqiwen** [comment]
the redis dump file should reimport, since the object length of zipzset/ziphash stored in ardb is double of real length.

**Comment by harutyundermenjyan** [comment]
Dear ardb Maintainer,
yes, seems really all problems around this(#248) issue has been solved.
Now I am going to try other DB Engines as well ; ) .
Thanks a lot.
