### ISSUE TITLE
Do you plan to support LUA-script?

### ISSUE THREAD

**Issue by mrniko** [yinqiwen/ardb#250]
Redis server supports LUA-script execution via EVAL command. Are you planning to add such command to ardb?

**Comment by yinqiwen** [comment]
any problems using lua with ardb?  All unit test cases in ardb are lua scripts.

**Comment by mrniko** [comment]
Can't find any mention about it support in wiki

**Comment by yinqiwen** [comment]
The commands not mentioned in wiki [ArdbCommands](https://github.com/yinqiwen/ardb/wiki/ARDB-Commands)   are supported and have same syntax & semantics in redis.

**Comment by mrniko** [comment]
> Lua Scripting support 

I haven't seen it.
