### ISSUE TITLE
build 0.9version on centos 7 no find libaio

### ISSUE THREAD

**Issue by luweijie007** [yinqiwen/ardb#253]
I build 0.9 version on centos 7 and test the forestdb perfermance .
but when I finish build forestdb 1.2 and has do this command:
sudo yum install libaio-devel 
nothing bad happen
but when I build ardb , I get problem:
forestdb-1.2/src/filemgr_ops_linux.cc:190：对  o_queue_init’未定义的引用
ardb/src/../deps/forestdb-1.2/build/libforestdb.a(filemgr_ops_linux.cc.o)：在函数‘_filemgr_aio_submit(async_io_handle*, int)’中：
and  this so on.
how can I install libaio ,can somebody help?

**Comment by yinqiwen** [comment]
Is there full error output?  It seems libaio related compile issue.

**Comment by luweijie007** [comment]
yes, It relate with libaio. compile log as follow:

**Comment by yinqiwen** [comment]
seems u need to edit makefile to add '-laio' to link libaio

**Comment by yinqiwen** [comment]
And about the undefined `UINT64_MAX` issue, it seems only happened with some gcc versions(not 3.4.5/4.8/5.3),   
I just add compiler flag '-D__STDC_LIMIT_MACROS' in makefile to fix it, can u rebuild with that?

**Comment by luweijie007** [comment]
I will try to do it ,
thanks you

**Comment by luweijie007** [comment]
![image](https://cloud.githubusercontent.com/assets/7186190/16223325/4e85bc8a-37cf-11e6-86bf-d034fd89bd4f.png)
add  flag '-D__STDC_LIMIT_MACROS' in where of makefile?

**Comment by yinqiwen** [comment]
https://github.com/yinqiwen/ardb/blob/0.9/src/Makefile#L114
