### ISSUE TITLE
Has LMDB part being tested?

### ISSUE THREAD

**Issue by ipapapa** [yinqiwen/ardb#254]
Tried to use the LMDB for the backend and we could get it running. RocksDB was working flawlessly.  Is ARDB with LMDB actively supported and tested?

**Comment by yinqiwen** [comment]
Most code in ardb is storage engine independent, which makes most bugs not storage engine related, and it's easy to add new storage engine support.  

Currently,  ardb with lmdb passed all lua unit test cases(in 'test' folder) & benchmark test by redis  tool
 'redis_benchmark'.
