### ISSUE TITLE
Problem compile in centos 6.x for rockdb engine

### ISSUE THREAD

**Issue by bdfy** [yinqiwen/ardb#255]
make 
resut:

`
ng.o  command/t_zset.o  db/codec.o  db/db.o  db/db_utils.o  db/engine.o  repl/master.o  repl/repl.o  repl/slave.o  repl/snapshot.o  repl/swal.o  /var/tmp/g/ardb-0.9/src/../deps/rocksdb-4.3.1/librocksdb.a /var/tmp/g/ardb-0.9/src/../deps/snappy-1.1.2/.libs/libsnappy.a /var/tmp/g/ardb-0.9/src/../deps/lua/src/liblua.a /var/tmp/g/ardb-0.9/src/../deps/jemalloc-4.1.0/lib/libjemalloc.a /var/tmp/g/ardb-0.9/src/../deps/snappy-1.1.2/.libs/libsnappy.a -lpthread  -lrt -lz -lbz2
/var/tmp/g/ardb-0.9/src/../deps/rocksdb-4.3.1/librocksdb.a(format.o): In function `LZ4_Uncompress':
/var/tmp/g/ardb-0.9/deps/rocksdb-4.3.1/./util/compression.h:550: undefined reference to `LZ4_decompress_safe'
/var/tmp/g/ardb-0.9/deps/rocksdb-4.3.1/./util/compression.h:550: undefined reference to `LZ4_decompress_safe'
/var/tmp/g/ardb-0.9/src/../deps/rocksdb-4.3.1/librocksdb.a(block_based_table_builder.o): In function `LZ4HC_Compress':
/var/tmp/g/ardb-0.9/deps/rocksdb-4.3.1/./util/compression.h:588: undefined reference to `LZ4_compressBound'
/var/tmp/g/ardb-0.9/deps/rocksdb-4.3.1/./util/compression.h:594: undefined reference to `LZ4_compressHC2_limitedOutput'
/var/tmp/g/ardb-0.9/src/../deps/rocksdb-4.3.1/librocksdb.a(block_based_table_builder.o): In function `LZ4_Compress':
/var/tmp/g/ardb-0.9/deps/rocksdb-4.3.1/./util/compression.h:508: undefined reference to `LZ4_compressBound'
/var/tmp/g/ardb-0.9/deps/rocksdb-4.3.1/./util/compression.h:512: undefined reference to `LZ4_compress_limitedOutput'
`

if add in ardb-0.9/src/Makefile  -llz4 flag in LIBS variable - it is solve problem

**Comment by yinqiwen** [comment]
lz4 is not a standard  library  in Linux, it seems u have installed lz4 in your system before, and rocksdb's makefile detected it.
