### ISSUE TITLE
slave can not sync with master

### ISSUE THREAD

**Issue by luweijie007** [yinqiwen/ardb#257]
version: 
ardb_version:0.8.6 
use rockdb as default 
but I found slave node can not sync with master
this log as follow:
![image](https://cloud.githubusercontent.com/assets/7186190/16219128/a264d200-37b6-11e6-99e5-e3875823ba8c.png)
this like a loop again
use redis-cli to connect client:
![image](https://cloud.githubusercontent.com/assets/7186190/16219348/48d3e2c4-37b8-11e6-9bcf-90932c4ac77c.png)

**Comment by luweijie007** [comment]
I make it work now, but I down not why this problem happend.
I  delete ../data and ../repl and restart slave node.
and before I  try to just delete ../data.  found that  still no sync

**Comment by luweijie007** [comment]
![image](https://cloud.githubusercontent.com/assets/7186190/16223119/6383472a-37ce-11e6-80ce-ab06045e0ed4.png)
but slave and master not still sync ,and infinite print log as above

**Comment by yinqiwen** [comment]
ardb 0.8.6 is too old(2 yeas ago), please use 0.9.2 instead.
