### ISSUE TITLE
when  switch storage engine , how about old data ?

### ISSUE THREAD

**Issue by luweijie007** [yinqiwen/ardb#258]
I have a question ,
How I need to do when I switch storage engine from rockdb to forestdb?
what happend to  the old data in old storage engine ? 
if I need to port old data ?

**Comment by yinqiwen** [comment]
u need to create a backup before switching storage engine, and reimport it later.   The data is stored in ${ARDB_HOME}/data/<storage_engine>, which can not be recognized by other storage engine.    
This wiki shows how to create a backup & restore by a backup. https://github.com/yinqiwen/ardb/wiki/Backup-Data
