### ISSUE TITLE
ardb 0.9.2 slaver can not sync retain data form master

### ISSUE THREAD

**Issue by luweijie007** [yinqiwen/ardb#259]
I use :
Ardb server v=0.9.2 bits=64 engine=rocksdb 
I master node has much data:380000 
and run a node as slave, and get this error:
![image](https://cloud.githubusercontent.com/assets/7186190/16303436/3c5f70d6-3983-11e6-91d5-99fa887fb728.png)
this finally, slave node can not received any retain  data from master. 
but if I set new key from master, the slave can sync this new set key.

**Comment by yinqiwen** [comment]
The IO error is reported by rocksdb lib, but maybe related with the wrong backup path(some unreadable chars in the path).    
Can u pull the latest code and test again?

**Comment by luweijie007** [comment]
I can test this issue ,thanks your work.

**Comment by yinqiwen** [comment]
Is `hlen` return 50000 at master and return 46379 at slave?

**Comment by luweijie007** [comment]
I will test on the last ardb version, tell your results
