### ISSUE TITLE
ardb 0.9.2 bug: hscan can not use

### ISSUE THREAD

**Issue by luweijie007** [yinqiwen/ardb#260]
I update ardb from 0.8.6 to 0.9.2 and found hscan return is not right:
![image](https://cloud.githubusercontent.com/assets/7186190/16329172/4d17393c-3a13-11e6-98b9-3da91dd671d2.png)

I use 0.8.6 to test again:
![image](https://cloud.githubusercontent.com/assets/7186190/16329187/5ffabea2-3a13-11e6-9b51-6eb0caabe98a.png)
this is ok

**Comment by yinqiwen** [comment]
This issue only happens with integer only hash fields, fixed.
