### ISSUE TITLE
question: How can I quit ardb server?

### ISSUE THREAD

**Issue by luweijie007** [yinqiwen/ardb#264]
what do I need to do If I want quit ardb ?
I need to do command "bgsave or save"?
I found some datas may been lost when restart ardb server, I will do some test to confirm

**Comment by yinqiwen** [comment]
No need to do bgsave/save before shutdown ardb if u using default storage engine's config. but if u disable rocksdb's wal, there would be data loss when restarting ardb.

**Comment by luweijie007** [comment]
u mean I just shutdown via redis-cli or kill ardb-server if I want to stop ardb-server?
what is mean disable rocksdb's wal？ can you tell me more detail ,thanks
ps: I  used default rocketdb config.

**Comment by luweijie007** [comment]
I found my been I run wrong config so I close it
