### ISSUE TITLE
SortedSet rounding score?

### ISSUE THREAD

**Issue by hnbanh** [yinqiwen/ardb#267]
Hi Yinqiwen,

I used sorted set with score is timestamp in milisec. Seem score value has been rounded. Does it affect the order of sorted set (most of scores are equal)? How can I get exact score of each element?

> ZRANGE TEST_ZSET 0 3 withscores
1) "100"
2) "1.467787e+12"
3) "101"
4) "1.467787e+12"
5) "102"
6) "1.467787e+12"
7) "103"
8) "1.467787e+12"

Thanks

**Comment by yinqiwen** [comment]
Can u use 'telnet' to get the real text protocol output?  "1.467787e+12" is double string printed by redis client .

**Comment by hnbanh** [comment]
This is telnet result

ZRANGE TEST_ZSET 0 3 withscores
*8
$3
100
$12
1.467787e+12
$3
101
$12
1.467787e+12
$3
102
$12
1.467787e+12
$3
103
$12
1.467787e+12

**Comment by hnbanh** [comment]
I also tried with another redis client (jedis - java) and I got the same result.

**Comment by yinqiwen** [comment]
"1.467787e+12" is server's string value for the stored score value(double), so every client would same value. I'll check the code of reply protocol encode part.

**Comment by yinqiwen** [comment]
Thanks for this bug report, it's fixed by latest commit.

**Comment by hnbanh** [comment]
Thank you for your instant reply. Double value is printed exactly.
