### ISSUE TITLE
SSCAN Iterator

### ISSUE THREAD

**Issue by maros** [yinqiwen/ardb#268]
When performing an SSCAN across a set containing more than 1000 members, only the first same 1000 values are returned regardless of the cursor:

```
127.0.0.1:11004> SSCAN KEYNAME 0
1) "44"
2)    1) "B000026DG8"
      2) "B000092KTO"
      3) "B00009Q148"
...
    999) "B005DMC7TC"
   1000) "B005DMC98G"

127.0.0.1:11004> SSCAN KEYNAME 44
1) "45"
2)    1) "B000026DG8"
      2) "B000092KTO"
      3) "B00009Q148"
````

**Comment by yinqiwen** [comment]
Thanks for this bug report, it's fixed by latest commit.

**Comment by maros** [comment]
Thank you for this lightning fast bug fix. I can confirm that SSCAN now behaves as expected
