### ISSUE TITLE
HSET function returns "OK" string

### ISSUE THREAD

**Issue by hnbanh** [yinqiwen/ardb#271]
Hi Yinqiwen,

Ardb's HSET function returns "OK" string instead of Integer value liked Redis.
> HSET mytesthash myfield "Hello"
OK

**Comment by yinqiwen** [comment]
u need to set 'redis-compatible-mode' to `yes` in ardb.conf
https://github.com/yinqiwen/ardb/wiki/ARDB-Commands

**Comment by hnbanh** [comment]
I got it. Thanks so much.
