### ISSUE TITLE
Lost data when restart ardb with LMDB storage

### ISSUE THREAD

**Issue by thoaivo** [yinqiwen/ardb#272]
Hi Yinqiwen,
I'm using ardb with LMDB on my production server. In the past, LMDB work well with stop/restart ardb service, but when I compile version 0.9.18 of ardb, I can't get my ardb data persistence anymore.
I see that you has previous post about default storage engine rocksdb:
"but if u disable rocksdb's wal, there would be data loss when restarting ardb."
As I understand that except rocksdb, any storage will not persistence. Can you correct me for that problem?
I'm using default file ardb.conf for testing with LMDB storage build.
Thank so much.

**Comment by yinqiwen** [comment]
u mean after restarting ardb, there is no any data in lmdb?

**Comment by thoaivo** [comment]
Yes, after stop and start ardb, I see there is no data.
Step to produce problem:
1. Start ardb with default configure (LMDB instance)

> [10844] 07-12 14:35:32,774 INFO Open db:0 success.
> [10844] 07-12 14:35:32,775 INFO Success to open lmdb at /data/ardb_07/lmdb
> [10844] 07-12 14:35:32,775 INFO Ardb init engine:lmdb success.
> [10844] 07-12 14:35:32,787 INFO Add cached snapshot:save-redis-snapshot.1883441567.5688240204084339936.1467331316
> [10844] 07-12 14:35:32,795 INFO Ardb will accept connections on 0.0.0.0:16385
> [10844] 07-12 14:35:32,795 INFO Ardb started with version 0.9.3

2. Import data from snapshoot to ardb
redis-cli -h 127.0.0.1 -p 16385 import /data/ardb-16385.rdb

3. Check for data in ardb
redis-cli -h 127.0.0.1 -p 16385 info

> # Keyspace
> db0:keys=8646

4. Stop ardb by ctrl + C (ardb running with daemonize=no)
5. Start ardb again
6. Check for data in ardb 
redis-cli -h 127.0.0.1 -p 16385 info

I see that there is no # Keyspace and db0:keys anymore, and using keys * return "(empty list or set)"
ardb make with command: 
`storage_engine=lmdb make`
Config file is change only home, port and datadir
`home /server/ardb-0.9
pidfile /server/tmp/ardb_07.pid
server[0].listen              0.0.0.0:16385
data-dir /data/ardb_07
`
Thank you.

**Comment by yinqiwen** [comment]
It's fixed by latest commit.

**Comment by yinqiwen** [comment]
The data is not actually lost, the root cause of this issue is that lmdb engine did not open the db after server restart, which make all read operations failed with nil result.

**Comment by thoaivo** [comment]
I was tested and seen that my data return. Thank for you support :smile:
