### ISSUE TITLE
Ardb hangs indefinitely after use of FLUSHDB

### ISSUE THREAD

**Issue by dustpuppyNGTI** [yinqiwen/ardb#277]
$ docker build -t ardb_bug .
$ docker run -it -p 16379:16379 ardb_bug

$ redis-cli -h 192.168.99.100 -p 16379
> AUTH secret
> SET boe boe
> FLUSHDB

This will hang the connection, any further connection will also fail on any command after (other than) AUTH.

Sorry for the .txt extensions, seems like GitHub doesn't like plain normal files. Remove the txt's to make the files work.

[ardb.conf.txt](https://github.com/yinqiwen/ardb/files/385835/ardb.conf.txt)
[Dockerfile.txt](https://github.com/yinqiwen/ardb/files/385836/Dockerfile.txt)

**Comment by yinqiwen** [comment]
What's the storage engine?  Currently, `flushdb/flushall` with leveldb/lmdb  would  iterate all existing keys and delete them, which may block the connection for a while.

**Comment by dustpuppyNGTI** [comment]
Docker initializes an empty database and the attached Dockerfile specifies storage_engine=leveldb. So it should be LevelDB with only a single key-value pair. As a side note, I only use the flushdb function myself during integration testing, on a production server I don't need it. So this isn't a blocking issue for me.

**Comment by yinqiwen** [comment]
fixed in last commit

**Comment by dustpuppyNGTI** [comment]
It works.
