### ISSUE TITLE
Wiredtiger FLUSHDB and FLUSHALL do not delete values

### ISSUE THREAD

**Issue by dustpuppyNGTI** [yinqiwen/ardb#278]
Wiredtiger backend DB does not delete values when executing FLUSHDB or FLUSHALL.

$ redis-cli -h 192.168.99.100 -p 16379
192.168.99.100:16379> AUTH secret
OK
192.168.99.100:16379> GET boe
(nil)
192.168.99.100:16379> SET boe boe
OK
192.168.99.100:16379> FLUSHDB
OK
192.168.99.100:16379> GET boe
"boe"
192.168.99.100:16379> SET one two
OK
192.168.99.100:16379> FLUSHDB
OK
192.168.99.100:16379> GET one
"two"
192.168.99.100:16379> GET lskfldsf
(nil)
192.168.99.100:16379> GET boe
"boe"
192.168.99.100:16379> QUIT

[ardb.conf.txt](https://github.com/yinqiwen/ardb/files/386446/ardb.conf.txt)
[Dockerfile.txt](https://github.com/yinqiwen/ardb/files/386447/Dockerfile.txt)

**Comment by dustpuppyNGTI** [comment]
Same problem exists for forestdb. lmdb, rocksdb and leveldb are fine. I couldn't test perconaft due to a problem with transparant hugepages and docker.

**Comment by dustpuppyNGTI** [comment]
In the log for forestdb: 
[6] 07-27 15:51:36,335 ERROR forestdb operation:rc = fdb_kvs_remove(local_ctx.fdb, ns.AsString().c_str()) error:(-32)there is an active open handle on the kvstore at line:560
[6] 07-27 15:51:46,560 ERROR forestdb operation:rc = fdb_kvs_remove(local_ctx.fdb, ns.AsString().c_str()) error:(-32)there is an active open handle on the kvstore at line:560

**Comment by yinqiwen** [comment]
Is this only forestdb related issue? I can't reproduce this with lmdb.

**Comment by yinqiwen** [comment]
And the fix for forestdb just been commit.

**Comment by dustpuppyNGTI** [comment]
I found this issue for both wiredtiger and forestdb. I couldn't test perconaft, the other backend dbs work fine.

**Comment by yinqiwen** [comment]
And the fix for wiredtiger just been commit.

**Comment by dustpuppyNGTI** [comment]
I ran a test on Wiredtiger. Am now getting an error setting a value on a previously wiped db.
192.168.99.100:16379> SET boe boe
OK
192.168.99.100:16379> FLUSHDB
OK
192.168.99.100:16379> GET boe
(nil)
192.168.99.100:16379> SET boe boe
(error) ERR no such key

Log says: [5] 07-29 15:33:36,223 ERROR Failed to open cursor on 0: No such file or directory

**Comment by yinqiwen** [comment]
pls check the latest commit for this issue

**Comment by JurgenNED** [comment]
It works
