### ISSUE TITLE
lmdb database_max_size not worked

### ISSUE THREAD

**Issue by 6api** [yinqiwen/ardb#279]
i modified config file
lmdb.options                  database_max_size=1G
and in data dir, the data.mdb file always 10g

**Comment by yinqiwen** [comment]
The comment from lmdb's code.    

	 * Any attempt to set a size smaller than the space already consumed
	 * by the environment will be silently changed to the current size of the used space.

**Comment by 6api** [comment]
so, is it mean for example:
i have data 2G
and set lmdb.options database_max_size=1G
then minutes(hours) later the data directory would almost be 2G?

**Comment by yinqiwen** [comment]
yes, u can not shrink the data file size, since there is risk to affect current data.
