### ISSUE TITLE
Ardb connection fails on SETs after failed AUTH

### ISSUE THREAD

**Issue by JurgenNED** [yinqiwen/ardb#280]
If you try to AUTH to a Ardb when no password has been configured it becomes impossible to perform SETs (and probably all other commands):

$ redis-cli -h 192.168.99.100 -p 16379
192.168.99.100:16379> AUTH boe
(error) ERR Unknown error 98996
192.168.99.100:16379> SELECT 0
(error) ERR Unknown error 98996
192.168.99.100:16379> SET boe boe
(error) ERR Unknown error 98996
192.168.99.100:16379> 

If you do the same with Redis this happens:
$ redis-cli -h localhost -p 6379
localhost:6379> AUTH boe
(error) ERR Client sent AUTH, but no password is set
localhost:6379> SET boe boe
OK
localhost:6379> GET boe
"boe"
localhost:6379> 

Tested with WiredTiger but I don't think it matters

**Comment by yinqiwen** [comment]
sorry for the delay, it's fixed by latest commit.

**Comment by JurgenNED** [comment]
tested. works
