### ISSUE TITLE
ardb couldn't find keys in lmdb after restarting ardb-server. Works fine in leveldb.

### ISSUE THREAD

**Issue by freedai** [yinqiwen/ardb#281]
After added key, I got
` redis-cli -p 16379 zrange zhost:WINMEDIA.FREECLIP.AEBN.NET 0 -1`
`1) "/:ABC"`

After restarting arbd-server, I got
` redis-cli -p 16379 zrange zhost:WINMEDIA.FREECLIP.AEBN.NET 0 -1`
`(empty list or set)`

**Comment by yinqiwen** [comment]
which storage engine are u using?

**Comment by freedai** [comment]
storage engine is lmdb

**Comment by yinqiwen** [comment]
can u use the latest source in git? this is a fixed issue 
https://github.com/yinqiwen/ardb/issues/272

**Comment by freedai** [comment]
Thanks. It's working in 24225be
