### ISSUE TITLE
sentinel no work on 1 master and two slaves

### ISSUE THREAD

**Issue by luweijie007** [yinqiwen/ardb#282]
I use 1 master and two slaves and 3 sentinels  for each ardb server
but I found that this sentinels  not selete new master from 2 slaves when I shutdown master node
How Can I do?  Any one ,can help me?

ps: I get flow message when I shutdown master:
![image](https://cloud.githubusercontent.com/assets/7186190/17360614/f8c2b48c-599e-11e6-8c20-30e6854bec53.png)

**Comment by luweijie007** [comment]
what about slaver of ardb?

**Comment by yinqiwen** [comment]
Is the message from redis-sentinel?

**Comment by yinqiwen** [comment]
For redis-sentinel compatible, ardb only need to reply pub/sub   correctly, i'll test ardb with sentinel.   
And waht's the sentinel version are u testing with?

**Comment by luweijie007** [comment]
this msssage get from redis-sentinel .
I use redis-cli login redis-sentinel and do : PSUBSCRIBE * .
about sentinel version:
![image](https://cloud.githubusercontent.com/assets/7186190/17387537/4026871c-5a27-11e6-9a6b-1a6839c653cf.png)
thanks yous

**Comment by yinqiwen** [comment]
i'll check latest redis-sentinel to reproduce this issue.

**Comment by luweijie007** [comment]
I use ardb version:
![image](https://cloud.githubusercontent.com/assets/7186190/17389910/a1cf562a-5a3a-11e6-827c-4dae6b6f7b0d.png)
and before I upgrade to 0.9 version but there are many bugs about 0.9 ,and I have to run 0.8 version now.

**Comment by yinqiwen** [comment]
i just tested latest ardb with latest redis-sentinel,  there is no any error.    

0.8.6 is pretty old, it's not compatible with 0.9, and it's not been maintained any more.

**Comment by luweijie007** [comment]
yes I test 0.8.6 with v=3.1.103 ,It is bad 
but v=3.0.1 of sentinel , is work right .so may been some uncompatible bwteen  0.8.6  of ardb and 3.1.1 of  sentinel .
one or two mouths before, I used to 0.9.X of ardb in work . and there is not enough stability for my work.
so I return to old version . and I use 0.8.6 version on production environment 
 I hope ardb 0.9 can reach to enough  stability  for production asap
thanks your works.
