### ISSUE TITLE
commands between MULTI and EXEC does not replicated to slave

### ISSUE THREAD

**Issue by e9485111** [yinqiwen/ardb#287]
I have a master and a slave configuration running ardb 0.8.6. Regular command or massive inserts runs fine but if I use pipeline mode which wraps commands between MULTI and EXEC. The results only show up on the master but not the slave.

Without pipeline
master:
redis 127.0.0.1:16379> set a b
OK

slave:
redis 127.0.0.1:16379> keys *
1) "a"

Using pipeline
master:
redis 127.0.0.1:16379> multi
OK
redis 127.0.0.1:16379> set a b
QUEUED
redis 127.0.0.1:16379> exec
1) OK

slave:
redis 127.0.0.1:16379> keys *
(empty list or set)

**Comment by yinqiwen** [comment]
it‘s a bug for the cached command's protocol buffer, just fixed in latest commit.
