### ISSUE TITLE
add feature

### ISSUE THREAD

**Issue by limbo127** [yinqiwen/ardb#288]
Hello, 
Is it possible to add qps-limit by connection or ip source client ?
Regards, 
Nicolas Prochazka

**Comment by yinqiwen** [comment]
It's a feature in previous version(0.8),  i just forgot to port it into current branch.

**Comment by limbo127** [comment]
I'm using 0.8, i can configure global qps-limit, but is it by client
connection ? ( Ip ? connection ? )
Regards

2016-09-27 3:44 GMT+02:00 yinqiwen <notifications@github.com>:

**Comment by yinqiwen** [comment]
The limit is for each listen server.  u can let ardb(0.8) listen on multi ports, and limit the qps for each listen port.

https://github.com/yinqiwen/ardb/blob/0.8/src/statistics.cpp#L71

**Comment by limbo127** [comment]
ok,
is it possible to add a per client connection limit in this case ?
Regards,
Nicolas

2016-09-27 11:09 GMT+02:00 yinqiwen <notifications@github.com>:

**Comment by yinqiwen** [comment]
yes, it's possible, but it would only be implemented in 0.9

**Comment by yinqiwen** [comment]
now  ardb-0.9 supoort qps-limit for listen-server/client ip/client connection

**Comment by limbo127** [comment]
ok,
thanks for that.

ardb 0.9 is not compatible with 0.8 branch, that means, that i cannot start
ardb-0.9 on a database ( LMBD ) manage by ardb 0.8 ?
Regards,
Nicolas

2016-09-30 11:02 GMT+02:00 yinqiwen <notifications@github.com>:

**Comment by yinqiwen** [comment]
0.9 can not serve with the data stored by 0.8 since the codec format have been changed.    
u can save the data stored in 0.8 as a redis dump file and then imported it into a 0.9 instance.

**Comment by mrluanma** [comment]
> u can save the data stored in 0.8 as a redis dump file and then imported it into a 0.9 instance.

Can you elaborate a little bit about this, seems my 0.8 deployment don't understand `SAVE redis` documented [here](https://github.com/yinqiwen/ardb/wiki/Backup-Data).

```
PING
+PONG
SAVE redis
-ERR wrong number of arguments for 'save' command
```

**Comment by yinqiwen** [comment]
@mrluanma  in 0.8, ardb use config 'backup-redis-format' to decide the dump file format, no arguments allowed for  `save` command.  The wiki is for v0.9.x
