### ISSUE TITLE
Unknow GeoSearch command by using Redis-cli, after upgrade v0.8.1 to 0.8.6

### ISSUE THREAD

**Issue by AjaxKong** [yinqiwen/ardb#289]
127.0.0.1:16379> geosearch
(error) ERR wrong number of arguments for 'geosearch' command
Ardb server v=0.8.1 bits=64 

127.0.0.1:6379> geosearch
(error) ERR unknown command:geosearch
Ardb server v=0.8.6 bits=64

**Comment by yinqiwen** [comment]
i think 0.8.6 is just 0.9.0.  in 0.9.x, ardb use the same geo command like redis.   
http://redis.io/commands#geo

**Comment by AjaxKong** [comment]
So u mean geosearch is not supported after v0.8.1?  We will gradually change the geosearch to redis standard command, however, is there currently any feasible fixing plan? I mean change some configuration or we hv to change the codes.

**Comment by AjaxKong** [comment]
sorry, I found v.8.6 supports geosearch...this command is not supported in v0.9.2....so any feasible fixing plan.

**Comment by yinqiwen** [comment]
the only way is to port the code into 0.9.x, but it's not easy.

**Comment by AjaxKong** [comment]
OK, got it....we will get to change the codes~~and we deupgraded the version on the server to 0.8.6...when the codes are ready, we will do the upgrade. And thx so much~
