### ISSUE TITLE
LTRIM bug

### ISSUE THREAD

**Issue by devvit** [yinqiwen/ardb#292]
Ardb(left) vs Redis2.8(right)

ltrim items
![](http://i.imgur.com/TtwbZe5.png)

ltrim 1000 items out of range
![](http://i.imgur.com/e8FLqgV.png)

ltrim offset
![](http://i.imgur.com/hMQGhkQ.png)

**Comment by yinqiwen** [comment]
fixed in last commit

**Comment by devvit** [comment]
lgtm
