### ISSUE TITLE
zrangebylex doesn't return any results for zset created with zunionstore

### ISSUE THREAD

**Issue by ikreymer** [yinqiwen/ardb#293]
Hi, I was testing on testing on the latest 0.9 branch, have a zset created from `zunionstore` of many other keys.

`zrange key 0 -1` and `zcard` work as expected, however, `zrangebylex` returns no results.

Can reproduce with any two keys joined with `zunionstore`

**Comment by foolenough** [comment]
fixed in latest commit.
