### ISSUE TITLE
Program terminated with signal 4, Illegal instruction.

### ISSUE THREAD

**Issue by johnny1952** [yinqiwen/ardb#295]
version:0.8.6
while execute ardb:

[root@cm107 ardb-old]# gdb ./ardb-server ./core.3053
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-51.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /opt/dzhyun/ardb-old/ardb-server...done.
[New LWP 3053]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./ardb-server ./ardb.conf'.
Program terminated with signal 4, Illegal instruction.
#0  0x00000000005b24d5 in initialize (this=<optimized out>, this=<optimized out>) at util/bloom.cc:354
354     util/bloom.cc: 没有那个文件或目录.
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.6-13.el7.x86_64 glibc-2.17-55.el7.x86_64 libgcc-4.8.2-16.el7.x86_64 libstdc++-4.8.2-16.el7.x86_64 zlib-1.2.7-15.el7.x86_64

more info:
(gdb) disassemble initialize
Dump of assembler code for function rocksdb::NewBloomFilterPolicy(int, bool):
   0x00000000005b24a0 <+0>:     push   %rbp
   0x00000000005b24a1 <+1>:     mov    %rsp,%rbp
   0x00000000005b24a4 <+4>:     push   %r12
   0x00000000005b24a6 <+6>:     mov    %esi,%r12d
   0x00000000005b24a9 <+9>:     push   %rbx
   0x00000000005b24aa <+10>:    mov    %edi,%ebx
   0x00000000005b24ac <+12>:    mov    $0x28,%edi
   0x00000000005b24b1 <+17>:    callq  0x407320 <_Znwm@plt>
   0x00000000005b24b6 <+22>:    movslq %ebx,%rdi
   0x00000000005b24b9 <+25>:    test   %rdi,%rdi
   0x00000000005b24bc <+28>:    movq   $0x6b0a30,(%rax)
   0x00000000005b24c3 <+35>:    mov    %rdi,0x8(%rax)
   0x00000000005b24c7 <+39>:    movq   $0x5b2600,0x18(%rax)
   0x00000000005b24cf <+47>:    mov    %r12b,0x20(%rax)
   0x00000000005b24d3 <+51>:    js     0x5b2530 <rocksdb::NewBloomFilterPolicy(int, bool)+144>
=> 0x00000000005b24d5 <+53>:    vcvtsi2sd %rdi,%xmm0,%xmm0
   0x00000000005b24da <+58>:    vmulsd 0xfe666(%rip),%xmm0,%xmm0        # 0x6b0b48
   0x00000000005b24e2 <+66>:    vmovsd 0xd3d0e(%rip),%xmm1        # 0x6861f8

**Comment by yinqiwen** [comment]
it seems that rocksdb crashed when try to init bloom filter. is this happened when ardb starting? 
and what's the config for rocksdb?

**Comment by johnny1952** [comment]
It happened while starting the ardb.

The rocksdb config :
#rocksdb's options, similar to leveldb's options
rocksdb.statistics_enable      yes
rocksdb.max_open_files         5000
#if 'use_bulk_load_options' set to 'yes', all other rocksdb's options below would be ignored 
rocksdb.use_bulk_load_options  no
rocksdb.block_cache_size       512m
rocksdb.block_size             0
rocksdb.write_buffer_size      128m
rocksdb.block_restart_interval 0
rocksdb.bloom_bits             10
rocksdb.batch_commit_watermark 1024
# Specify the rocksdb compression
# This can be one of snappy/none
rocksdb.compression            snappy
rocksdb.skip_log_error_on_recovery yes
#0 means no limit
rocksdb.flush_compact_rate_bytes_per_sec  0
rocksdb.hard_rate_limit        2.0
rocksdb.disableWAL             no
rocksdb.max_manifest_file_size 2G
#The compaction style, could be set to 'level' or 'universal'
rocksdb.compaction_style       level
rocksdb.disable_auto_compactions no

**Comment by johnny1952** [comment]
another question:
The ardb works well on my another CentOS7 server the same as the server where problem occurs .

**Comment by johnny1952** [comment]
OK,another thing is,
I've download v0.8, and it works well.

**Comment by yinqiwen** [comment]
the crash is in rocksdb, and the [rocksdb code](https://github.com/facebook/rocksdb/blob/master/util/bloom.cc#L364) where is crashed seems  ok with no crash bug.

**Comment by yinqiwen** [comment]
0.8.6 is not a release tag, is it the latest code in branch '0.8'?     
ardb development have been switch to 0.9 several month ago, and 0.9 is not compatible with 0.8.
