### ISSUE TITLE
Odd behaviour of zrevrange

### ISSUE THREAD

**Issue by ualtinok** [yinqiwen/ardb#296]
Hi,

ARDB has undocumented (if documented I couldn't find it) different behaviour for zrevrange.

From redis documentation:
> The elements are considered to be ordered from the highest to the lowest score.

However in ARDB the items sorted after selecting the range, so that if there is 6 items in zset and we try to retrieve top 3 of them with zrevrange, it should normally return the highest 3 scored items from the zset. However it just returns lowest scored 3 items in reverse order.

Example Case:

zadd TEST 0 A
zadd TEST 1 B
zadd TEST 2 C
zadd TEST 3 D
zadd TEST 4 E
zadd TEST 5 F

ARDB output:
zrevrange TEST 0 3 WITHSCORES
1) "D"
2) "3"
3) "C"
4) "2"
5) "B"
6) "1"
7) "A"
8) "0"

Redis ouput:

zrevrange TEST 0 3 WITHSCORES
1) "F"
2) "5"
3) "E"
4) "4"
5) "D"
6) "3"
7) "C"
8) "2"

**Comment by yinqiwen** [comment]
fixed by latest commit

**Comment by ualtinok** [comment]
It's indeed fixed, maybe we can close the issue.
