### ISSUE TITLE
zAdd doesn't follow redis spec

### ISSUE THREAD

**Issue by ualtinok** [yinqiwen/ardb#298]
Hi,

According to redis docs zadd:

> Return value
> Integer reply, specifically:
> The number of elements added to the sorted sets, not including elements already existing for which the score was updated.

However in ARDB zadd command return Integer reply 1 in all cases. It should return 0 if the item already exists and only score is updated.

**Comment by yinqiwen** [comment]
have u try to set 'redis-compatible-mode' to yes in ardb.conf? the default value is no

**Comment by ualtinok** [comment]
Oh I did set but apparently I was using wrong configuration. Sorry, closing the issue.
