### ISSUE TITLE
Cross Compiler Support - ARMv7

### ISSUE THREAD

**Issue by CCJH** [yinqiwen/ardb#301]
I'm trying to cross compile ARDB for an ARMv7 platform using the GCC 4.9 Linaro toolchain but keep getting this error, 

common/coro/coro.c:238:11: error: #error unsupported architecture
          #error unsupported architecture

Using the following make command,

make AR=/opt/toolchains/gcc-linaro-4.9-2014.11/bin/arm-linux-gnueabihf-ar LD=/opt/toolchains/gcc-linaro-4.9-2014.11/bin/arm-linux-gnueabihf-ls CC=/opt/toolchains/gcc-linaro-4.9-2014.11/bin/arm-linux-gnueabihf-gcc CXX=/opt/toolchains/gcc-linaro-4.9-2014.11/bin/arm-linux-gnueabihf-g++ XC_HOST="x64-unknown-linux" XC_HOST="arm-unknown-linux"

**Comment by yinqiwen** [comment]
Can u try use macro 'CORO_UCONTEXT' to disable the asm code in coro lib? 

https://github.com/yinqiwen/ardb/blob/0.9/src/Makefile#L146

**Comment by CCJH** [comment]
That got me past that issue but, I also had to comment out the following in the RocksDB makefile,

OPT += -momit-leaf-frame-pointer

Seems to have built okay on my ARM platform, cross compiling on host seems to have a lot of problems, most I can get round by building the dependencies individually before trying to build ardb but i'm still having some problems with the linker,

/opt/toolchains/gcc-linaro-4.9-2014.11/bin/arm-linux-gnueabihf-g++ -o ardb-test  db/rocksdb/rocksdb_engine.o  ../test/test_main.o config.o cron.o logger.o network.o types.o statistics.o  common/channel/channel.o  common/channel/channel_handler_context.o  common/channel/channel_helper.o  common/channel/channel_pipeline.o  common/channel/channel_service.o  common/channel/socket/clientsocket_channel.o  common/channel/socket/datagram_channel.o  common/channel/socket/serversocket_channel.o  common/channel/socket/socket_channel.o  common/channel/fifo/fifo_channel.o  common/channel/codec/delimiter_frame_decoder.o  common/channel/codec/dir_sync_decoder.o  common/channel/codec/int_header_frame_decoder.o  common/channel/codec/redis_command_codec.o  common/channel/codec/redis_reply_codec.o  common/channel/codec/redis_reply.o  common/channel/timer/timer_channel.o  common/channel/timer/timer.o  common/channel/timer/timer_task_queue.o  common/channel/signal/signal_channel.o  common/channel/signal/soft_signal_channel.o  common/util/config_helper.o  common/util/datagram_packet.o  common/util/file_helper.o  common/util/math_helper.o  common/util/mmap.o  common/util/network_helper.o  common/util/socket_address.o  common/util/string_helper.o  common/util/system_helper.o  common/util/time_helper.o  common/util/exception/api_exception.o  common/thread/event_condition.o  common/thread/thread.o  common/coro/coro_channel.o  common/coro/scheduler.o  common/buffer/buffer.o  common/buffer/buffer_helper.o  common/geo/geohash_helper.o  common/util/murmur3.o  common/util/rand.o  common/util/sds.o  common/util/sha1.o  common/coro/coro.o  common/redis/crc64.o  common/redis/endianconv.o  common/redis/intset.o  common/redis/lzf_c.o  common/redis/lzf_d.o  common/redis/ziplist.o  common/redis/zipmap.o  common/geo/geohash.o  common/channel/redis/ae.o  common/channel/redis/zmalloc.o   command/connection.o  command/geo.o  command/hyperloglog.o  command/keys.o  command/lua_scripting.o  command/merge.o  command/migrate.o  command/pubsub.o  command/server.o  command/slowlog.o  command/sort.o  command/t_bitset.o  command/t_hash.o  command/t_list.o  command/transaction.o  command/t_set.o  command/t_string.o  command/t_zset.o  db/codec.o  db/db.o  db/db_utils.o  db/engine.o  repl/master.o  repl/repl.o  repl/slave.o  repl/snapshot.o  repl/swal.o  /home/sonardyne/pilot/libraries/ardb/src/../deps/rocksdb-4.3.1/librocksdb.a /home/sonardyne/pilot/libraries/ardb/src/../deps/snappy-1.1.2/.libs/libsnappy.a /home/sonardyne/pilot/libraries/ardb/src/../deps/lua/src/liblua.a /home/sonardyne/pilot/libraries/ardb/src/../deps/jemalloc-4.1.0/lib/libjemalloc.a /home/sonardyne/pilot/libraries/ardb/src/../deps/snappy-1.1.2/.libs/libsnappy.a -lpthread  -lrt -lz -lbz2  -L/opt/toolchains/gcc-linaro-4.9-2014.11/sysroot/lib/arm-linux-gnueabihf/
/opt/toolchains/gcc-linaro-4.9-2014.11/bin/../lib/gcc/arm-linux-gnueabihf/4.9.3/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lz
/opt/toolchains/gcc-linaro-4.9-2014.11/bin/../lib/gcc/arm-linux-gnueabihf/4.9.3/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lbz2

**Comment by yinqiwen** [comment]
libbz2 & libz is compress library in most system, u can remove '-lz -lbz2' in src/Makefile if u not installed them in your systemt.

**Comment by khaledkbadr** [comment]
Same issue when I tried to make on `Ubuntu 16.04`

**Comment by yinqiwen** [comment]
@khaledkbadr   install libz  in ubuntu

**Comment by khaledkbadr** [comment]
`zlib-devel` in Fedora
