### ISSUE TITLE
Ordering of data stored and queried in hashes is different

### ISSUE THREAD

**Issue by ipapapa** [yinqiwen/ardb#303]
I am looking into how the data are stored and queried in RocksDB through ARDB. I tried the following experiment. I used HMSET into two ARDB nodes with 150 values. When I used HSCAN with COUNT 200 in both nodes the order of the response was different across those nodes. Is there a reason why the data are not returned in the order they were stored?

**Comment by yinqiwen** [comment]
Ardb use rocksdb's prefix api for hscan/sscan/zscan,  while the `iterators are not guaranteed a total order of all keys.`
https://github.com/facebook/rocksdb/wiki/Prefix-Seek-API-Changes

To enable total order for  hscan/sscan/zscan, u can do that like `scan` command which just set `iterate_total_order=1` to enable total order. 
https://github.com/yinqiwen/ardb/blob/0.9/src/command/keys.cpp#L236

**Comment by ipapapa** [comment]
Currently setting the `iterate_total_order` translates to `total_order_seek = true` in the [RocksDB engine](https://github.com/yinqiwen/ardb/blob/51646a29b698a119b9fd11e89d78654ac9947d2a/src/db/rocksdb/rocksdb_engine.cpp#L1204). However, according to the [Prefix seek API](https://github.com/facebook/rocksdb/wiki/Prefix-Seek-API-Changes), it should be `total_order_mode`.

**Comment by ipapapa** [comment]
For the first: https://github.com/facebook/rocksdb/issues/1613

**Comment by yinqiwen** [comment]
add a config 'scan-total-order ' in latest commit

**Comment by ipapapa** [comment]
Thank you!
