### ISSUE TITLE
Issues with master/slave replication between ARDB nodes

### ISSUE THREAD

**Issue by ipapapa** [yinqiwen/ardb#304]
Using ARDB master/slave replication (storage engine is RocksDB). Setting an ARDB node as a slave of a master ARDB node. 

Master is in the `state=wait_bgsave` for a long time and every after INFO command I see that either `connected_slaves: 0` or  `connected_slaves: 1`. It seems master loses connectivity with slave or vice versa. Not sure if this is related to the following log
`[13161] 12-16 21:23:54,075 ERROR Failed to backup rocksdb for reason:IO error: //backup/master-rocksdb-backup/private/1.tmp/MANIFEST-002495: No such file or directory`

Moreover, why does the `ardb.swal.log` is a `.log` and is a binary? Shouldn't there be a different naming convention?

**Comment by yinqiwen** [comment]
is there full log for this issue?  

and `ardb.swal.log` is just circle redis protocol log file with fix size.

**Comment by ipapapa** [comment]
There was some capacity issue when this happened, so I am closing this.
