### ISSUE TITLE
List在频繁读写时经常出问题

### ISSUE THREAD

**Issue by vlike** [yinqiwen/ardb#305]
上周clone出来新编译的版本,rocksdb引擎,
用List作为队列的场景,因为经常往列表里push数据,也经常从队列里pop数据,
若干时间后,就会出现问题.
上次出问题的表现为:
无论用lpop,rpop都能获得数据,但数据没有真实被pop出来,每次pop得到的结果都是一样,llen查询记录数也没有变化,重启也没作用

**Comment by vlike** [comment]
补充一下版本
Ardb server v=0.9.4 bits=64 engine=rocksdb


类似问题
https://github.com/yinqiwen/ardb/issues/231

**Comment by yinqiwen** [comment]
u mean lpop/rpop return a value but the list is not modified?   is the list modified by commands 'lrem/linsert'?

**Comment by vlike** [comment]
no, never use those commands,
just simple push/pop

**Comment by yinqiwen** [comment]
commit a fix for internal object pool.
https://github.com/yinqiwen/ardb/blob/0.9/src/common/channel/codec/redis_reply.cpp#L65
