### ISSUE TITLE
Slow "SCAN 0" command

### ISSUE THREAD

**Issue by maros** [yinqiwen/ardb#309]
I don't know if this is due to a bug, or due to a limitation of RocksDB, but calling "SCAN 0" or "SCAN 0 MATCH SOMETHING:*" on a database with ~7Mio keys is very slow and takes aprox 30sec (on a smaller server with 64G of Ram). 

However, calling SCAN with subsequent indices eg. "SCAN 1" produces the desired results in just a few milliseconds.

**Comment by yinqiwen** [comment]
is most the keys hash/set/list/zset with  large length?  
'hash/set/list/zset' stored in rocksdb with many key/value paris, while make 'scan' slow to iterate to next key.

**Comment by maros** [comment]
yes, most keys are SETs
