### ISSUE TITLE
Failed to `save redis`

### ISSUE THREAD

**Issue by monsterxx03** [yinqiwen/ardb#311]
Ardb server v=0.9.4 bits=64 engine=rocksdb

I imported  a 8GB rdb file into ardb, then try to execute `save redis`, get error like:

    ERROR Previous key:user_article-1.0:user:1014816 with type:7 is not complete dump, 1 missing in 1 elements
    ERROR Failed to write dump file for reason code:-2
    WARN Failed to save snapshot file with type:redis
    WARN Remove snapshot file:/home/ubuntu/ardb/backup/save-redis-snapshot.1487327103001.tmp

>>> type  user_article-1.0:user:1014816
set
>>> smembers user_article-1.0:user:1014816
(empty list or set)

redis-check-rdb:

    [offset 0] Checking RDB file dump_12000.rdb
    [offset 11] Selecting DB ID 0
    [offset 8743064873] Checksum OK
    [offset 8743064873] \o/ RDB looks OK! \o/
    [info] 55575306 keys read
    [info] 10235521 expires
    [info] 1368097 already expired

I tried to laucn a redis-server(3.2.8) from same rdb, keyspace shows:

db0:keys=54219642,expires=8879857,avg_ttl=2317224653

try to execute `smember` on redis for this key,  I can get result, just one item:  "3"

**Comment by monsterxx03** [comment]
Also, when I run compactall on ardb, I see things in log:

     Cost 4ms to delete 110 keys.

Whey ardb will delete keys?

**Comment by yinqiwen** [comment]
There is a background task to scan keys with ttl, which would delete expired keys.

**Comment by monsterxx03** [comment]
I reproduced the set problem.

Launch a redis-server(tested on 3.0.0 and 3.7.8).

>> sadd set1 1

then launch ardb-server, make it slaveof redis-server

>> smember set1  
(empty list or set)

Seems it only happen when set only contain  number value

If `sadd set1  1 a b` on redis-server,  then value will be right in ardb

`sadd set 1 2 3`, value will be empty on ardb.

**Comment by monsterxx03** [comment]
Figure out the problem. 
Caused by redis settings: set-max-intset-entries

Changed it to value 0, then ardb decode will work on small integer. ardb didn't handle this encoding case.

What's the redis version ardb based on?  My production redis is redis.3.0.0 with rdb version 6, maybe I should test against your redis version.

**Comment by yinqiwen** [comment]
fixed in lasted commit, which cause by a stupid mistake.

**Comment by monsterxx03** [comment]
Great thanks, I'll test it again

**Comment by praveenmak** [comment]
May I know how to import dump.rdb to rocksdb in ardb ?

I tried this,
import $HOME/dump.rdb <--- my redis rdb is my home directory.
(error) ERR Import snapshot failed.

**Comment by yinqiwen** [comment]
the server does not translate $HOME to real path

**Comment by yinqiwen** [comment]
the server does not translate $HOME to real path

**Comment by yinqiwen** [comment]
the server does not translate $HOME to real path

**Comment by yinqiwen** [comment]
the server does not translate $HOME to real path
