### ISSUE TITLE
use rocksdb as storage engine then expire hash struct has no effect

### ISSUE THREAD

**Issue by xmm1989218** [yinqiwen/ardb#312]
use rocksdb as storage engine then expire hash struct has no effect
for example:
hset aa bb cc
expire aa 10
after 10 seconds later, aa also can access, 
but when I use ttl aa,it will return -2, then I hgetall aa, it disappear

**Comment by yinqiwen** [comment]
for rocksdb, only the background compact task  would do the expire task. u can use 'compactall' to trigger the operation.   
'ttl' is a common read operation which would check the key expiration first.
