### ISSUE TITLE
save ardb with leveldb not working properly when having several namespaces

### ISSUE THREAD

**Issue by daddyz** [yinqiwen/ardb#314]
We recently started to use ardb + leveldb. We have lot's of data separated logically to 4 "redis dbs" (select 1,2,3,4). Our setup includes 1 master and several slaves, once slave was connected from the beginning, all is good, when we had to add new slave, there was a problem, slave asks for full dump, gets it and start working, but full dump is not good, it takes only first namespace (db).
As far as I figured out ```Snapshot::ArdbSave``` function does iterate on available namespaces, but ```g_db->GetEngine()->Find(dumpctx, empty)``` returns iterator that is not valid (except for first namespace). In ```LevelDBEngine::Find``` it gets to last line in function, but iterator is invalid after ```rocksiter->SeekToFirst();```.

Steps to reproduce:
* compile with leveldb
* use default config
* connect
* select 1 && set 1 1
* select 2 && set 2 2
* save ardb

btw, don't know why, but save backup returns error

Any help will be appreciated

**Comment by yinqiwen** [comment]
fixed in latest commit

**Comment by daddyz** [comment]
@yinqiwen Thanks, this helped
