### ISSUE TITLE
Does cluster support work?

### ISSUE THREAD

**Issue by lwansbrough** [yinqiwen/ardb#320]
I see there is a cluster branch but it was last updated 9 months ago. I also see it's been merged into master. So does clustering work? Thanks!

**Comment by yinqiwen** [comment]
1. the cluster branch is not working now.
2. u can use redis cluster proxy like dynomite/codis  before redis/ardb.

**Comment by lwansbrough** [comment]
@yinqiwen Interesting, thanks for the recommendation.
