### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by ipapapa** [yinqiwen/ardb#321]
1. Does ARDB support rotating logs? or does the log file becomes larger and larger? 
2. Can the log level change during runtime?

**Comment by yinqiwen** [comment]
1. TWO rotate logging file, max file size is 100MB
https://github.com/yinqiwen/ardb/blob/0.9/src/logger.cpp#L49-L50

2. Not supported now.

**Comment by shailesh33** [comment]
for changing log level at runtime, what do you suggest should be the right approach for ardb? Expose a control port with rest api? or have a seperate redis command specifically for this?

**Comment by yinqiwen** [comment]
I just forgot that redis command `config set loglevel DEBUG`, which could change log level at runtime. Actually, many configurations defined in `ardb.conf` could be changed at runtime.

**Comment by ipapapa** [comment]
ARDB seems to write on top of the previous log file instead of starting a new when restarting it. It would be nice to make it start a new log file instead of appending the previous one.

**Comment by shailesh33** [comment]
Appending to be specific

**Comment by yinqiwen** [comment]
The logger would remove oldest log file(ardb-server.log.1), then rename current ardb-server.log to ardb-server.log.1, then create a new log file ardb-server.log.
https://github.com/yinqiwen/ardb/blob/0.9/src/logger.cpp#L89-L90

**Comment by ipapapa** [comment]
Fixed that in our env
