### ISSUE TITLE
what does Invalid key mean?

### ISSUE THREAD

**Issue by daddyz** [yinqiwen/ardb#324]
we've tried lmdb engine, on all sets we see error "Invalid key".
As I understand it's in src/db/codec.cpp on line 232.
What does it mean and what should we do to fix it?

**Comment by yinqiwen** [comment]
this seems a bug . which command or operation trigger this error log?

**Comment by daddyz** [comment]
```setex 12125551234 999 1```
I managed to see this error in lmdb and wiredtiger. other backends (except for perconaft, didn't try it) didn't show this error.

**Comment by yinqiwen** [comment]
fixed in latest commit
