### ISSUE TITLE
BGSave file name

### ISSUE THREAD

**Issue by tigerzhang** [yinqiwen/ardb#326]
BGSAVE 默认会使用固定的文件名：
```
       if (type == BACKUP_DUMP)
        {
            snprintf(path, sizeof(path) - 1, "%s/save-%s-backup", g_db->GetConf().backup_dir.c_str(), g_engine_name);
        }
        else
        {
            snprintf(path, sizeof(path) - 1, "%s/save-%s-snapshot", g_db->GetConf().backup_dir.c_str(), type2str(type));
        }
```

这样会造成两个问题：

1. 多次运行 BGSAVE，但是只会有一个备份文件；
2. 当备份数量达到设置的上限是，备份文件会被删除，会造成没有备份文件；

**Comment by yinqiwen** [comment]
This behavior is following redis's design doc, which there is only ONE dump file for redis.
`By default Redis saves snapshots of the dataset on disk, in a binary file called dump.rdb. You can configure Redis to have it save the dataset every N seconds if there are at least M changes in the dataset, or you can manually call the SAVE or BGSAVE commands.`
https://redis.io/topics/persistence#snapshotting

**Comment by TigerZhang** [comment]
1. 在 ardb，BGSAVE 和 SAVE 的行为是不一样的，SAVE 会产生多个文件。
2. 第二个是一个 bug，多次执行 BGSAVE 后，dump 文件会在 BGSAVE 结束后被删除，最后 BGSAVE 执行成功了，但是没有 dump 文件。

**Comment by yinqiwen** [comment]
fixed in latest commit.
