### ISSUE TITLE
ardb crashes on start (Bus error (core dumped))

### ISSUE THREAD

**Issue by unoexperto** [yinqiwen/ardb#329]
Hey guys!

I'm trying to create docker image with ardb and for some reason it's crashing on start. I tried to build it with RocksDB and LevelDB. Here is my `Dockerfile`

```
FROM alpine:latest

MAINTAINER unoexperto <unoexperto.support@mailnull.com>

RUN echo "@testing http://nl.alpinelinux.org/alpine/edge/testing" >>/etc/apk/repositories

RUN apk update && \
    apk add gcc && \
    apk add --virtual .build-deps autoconf make g++ linux-headers git && \
    apk add ca-certificates && \
    update-ca-certificates && \
    apk add openssl

RUN apk add --update --no-cache zlib zlib-dev bzip2 bzip2-dev snappy snappy-dev lz4 lz4-dev zstd@testing zstd-dev@testing jemalloc jemalloc-dev libtbb-dev@testing libtbb@testing

RUN mkdir -p /usr/src/ardb

RUN git clone --depth 1 https://github.com/yinqiwen/ardb.git /usr/src/ardb && \
  make -C /usr/src/ardb

RUN apk del .build-deps

RUN mkdir /ardb_home

RUN sed -e 's@home .*@home /ardb_home@' -i /usr/src/ardb/ardb.conf

EXPOSE 16379
VOLUME /ardb_home
WORKDIR /ardb_home

CMD ["/usr/src/ardb/src/ardb-server", "/usr/src/ardb/ardb.conf"]
```

All I get is

```
Bus error (core dumped)
```

What am I missing ?

**Comment by unoexperto** [comment]
@yinqiwen Could you please comment when you have a chance ?

**Comment by yinqiwen** [comment]
@unoexperto  have u modified `home` in ardb.conf?

**Comment by unoexperto** [comment]
@yinqiwen Yes. I changed it from `..` to absolute path `/ardb_home`.

**Comment by yinqiwen** [comment]
@unoexperto  i just test it and found this is a jemalloc issue, u can use `MALLOC=libc make` to use standard malloc library to  instead jemalloc.

**Comment by unoexperto** [comment]
Yep. That helped. I also tried jemalloc 4.5.0 which also crashes. Could you please keep this bug open and close it when you confirm jemalloc is fixed ? I'll rebuild my container then.

**Comment by mdhheydari** [comment]
@yinqiwen Is there any way to use jemalloc? with any other version maybe?

**Comment by yinqiwen** [comment]
latest commit fix this bug.

**Comment by unoexperto** [comment]
Awesome!!
