### ISSUE TITLE
ardb is multithreading but redis is single thread, is it right?

### ISSUE THREAD

**Issue by spiderpoison** [yinqiwen/ardb#331]
My application use redis right now, I want to use ardb and rocksdb instead of redis. but redis is single thread and rocksdb is multithreading, so that means i can not replace directly ?

**Comment by yinqiwen** [comment]
u can use only ONE thread in ardb.   
and in redis, most features does not reply on the one thread feature, u can use most commands in  multithreading env without any problem.

**Comment by anhduongxanh63** [comment]
If we run ardb in multi-threading env, some incr operation is still thread safe/atomic?
