### ISSUE TITLE
keyscount 命令慢

### ISSUE THREAD

**Issue by xiquan-wu** [yinqiwen/ardb#335]
在约500W+ 数据量情况下使用keyscount * 统计key数据量，速度相当慢，而且也极占用CPU。请问keyscount原理是扫描全库吗？有其他办法可以快速统计key数据量吗？

引擎：wiredtiger

**Comment by yinqiwen** [comment]
keyscount have  O(N) complexity like  keys command.   there is no faster way to get the count.

**Comment by xiquan-wu** [comment]
是否会在下一版本考虑在info加入keys等参数呢？

**Comment by unoexperto** [comment]
@xiquan-wu I believe there is already keys count in INFO but its value looks incorrect to me. Perhaps @yinqiwen can comment. I use RocksDB engine.

As per your initial question I recommend having separate counter. I have ~78M hashes and getting count is also slow.
