### ISSUE TITLE
Redis incompatibilities

### ISSUE THREAD

**Issue by mannol** [yinqiwen/ardb#339]
**RENAME**
RENAME command returns simple string reply as specified [here](https://redis.io/commands/rename).
In ardb that same command returns 1 or 0, depending if the key is renamed or not respectively.

**HSET**
HSET command returns integer value as specified [here](https://redis.io/commands/hset).
In ardb that same command returns simple string reply.

**HDEL**
HDEL command returns integer value as specified [here](https://redis.io/commands/hset).
In ardb that same command returns simple string reply.

**SADD**
SADD command returns integer value as specified [here](https://redis.io/commands/sadd).
In ardb that same command returns simple string reply.

**Comment by yinqiwen** [comment]
for `rename`, the latest commit fix it.  
and for other commands, there is  'redis-compatible-mode' in ardb.conf.  for some commands, use simple response would have higher performance.
