### ISSUE TITLE
Can't use lua command, like EVAL

### ISSUE THREAD

**Issue by spiderpoison** [yinqiwen/ardb#342]
127.0.0.1:16379[1]> eval "return redis.call('HSET','names:0:10','bar','nn')" 0
(integer) 0
127.0.0.1:16379[1]> hget names:0:10 bar
(nil)
127.0.0.1:16379[1]> eval "return redis.call('HGET','names:0:10','bar')" 0
"nn"

There is something like hset by eval, only can hget by eval...

**Comment by yinqiwen** [comment]
the key is written to db 0 , fixed in latest commit.
