### ISSUE TITLE
auto remove snapshot ?

### ISSUE THREAD

**Issue by xiquan-wu** [yinqiwen/ardb#343]
使用过程中发现snapshot被自动删除，但并未达到maxsnapshots值，自动删除snapshot的代码如下，请问在什么情况下会自动删除snapshot？snapshot与ReplLog存在什么关系呢，为什么ReplLog offset 会引起删除snapshot？

[12791] 06-07 12:18:58,106 WARN Remove snapshot:/home/ardb-0.9.4/backup/save-rocksdb-backup.114445363293.10497088338683193929.1496803312 since it's too old with offset:114445363293

 LockGuard<ThreadMutexLock> guard(m_snapshots_lock);
        SnapshotArray::iterator it = m_snapshots.begin();
        while (it != m_snapshots.end())
        {
            Snapshot* s = *it;
            if (s == NULL || (s->CachedReplOffset() < g_repl->GetReplLog().WALStartOffset()))
            {
                if (NULL != s)
                {
                    WARN_LOG("Remove snapshot:%s since it's too old with offset:%llu", s->GetPath().c_str(), s->CachedReplOffset());
                    s->Remove();
                }
                DELETE(s);
                it = m_snapshots.erase(it);
            }
            else
            {
                it++;
            }
        }

**Comment by yinqiwen** [comment]
`CachedReplOffset` is represent  the redis commands sequence  when this snapshot created, and the `WALStartOffset` is represent the oldest redis command sequence in the replication log.  if  `CachedReplOffset` < `WALStartOffset` , this means the server can not recover from the snapshot + replication log since there is redis command loss.

**Comment by xiquan-wu** [comment]
您的意思是使用snapshot + ardb.swal.log能还原实时的ardb，那如果我使用备份，还原时只需要还原到上一次的备份点，我可以把以下代码注解吗？

while (it != m_snapshots.end())
        {
            Snapshot* s = *it;
            if (s == NULL || (s->CachedReplOffset() < g_repl->GetReplLog().WALStartOffset()))
            {
                if (NULL != s)
                {
                    WARN_LOG("Remove snapshot:%s since it's too old with offset:%llu", s->GetPath().c_str(), s->CachedReplOffset());
                    s->Remove();
                }
                DELETE(s);
                it = m_snapshots.erase(it);
            }
            else
            {
                it++;
            }
        }
