### ISSUE TITLE
 rocksdb segfault 

### ISSUE THREAD

**Issue by xiquan-wu** [yinqiwen/ardb#349]
kernel: rocksdb:bg1[12793]: segfault at 7ff6484002e3 ip 0000000000577a3e sp 00007ff649dfce60 error 6 in ardb-server[400000+41c000]

排查出错日志为DBImpl::MaybeDumpStats，请问有见过这问题吗？

**Comment by yinqiwen** [comment]
what's the output of `addr2line -e ./ardb-server 7ff6484002e3`?
