### ISSUE TITLE
Any plans to support RDB format version 8?

### ISSUE THREAD

**Issue by tipiirai** [yinqiwen/ardb#361]

**Comment by yinqiwen** [comment]
fixed  in  https://github.com/yinqiwen/ardb/commit/1e93a3e71a75c9f1bba17873ba1f06c20394702c

**Comment by tipiirai** [comment]
Very cool – thanks! 

Here's a use case: a highly performant (and costly) Redis can now act as a master and if it fails there is ARDB slave replying on a much cheaper server.
