### ISSUE TITLE
Inconsistent Key Count after BGSAVE and IMPORT

### ISSUE THREAD

**Issue by rjonesxmoz** [yinqiwen/ardb#363]
I am trying to keep 2 RocksDB databases consistent (they are rarely updated). To do this, I was hoping to simply run BGSAVE on the first machine via ardb and then IMPORT that snapshot into the second machine using ardb.

Unfortunately, I get inconsistent key counts each time I run this. 

Is there a better way to copy one to the other?

**Comment by yinqiwen** [comment]
is the key count reported by 'info' command?

**Comment by rjonesxmoz** [comment]
I was using dbsize, but the info command yields:

# Keyspace
db0:keys=939859164

# Keyspace
db0:keys=877488365

**Comment by ipapapa** [comment]
RocksDB provides only an estimated number of keys stored in the column family and it is affected by the number of pending compactions. See https://github.com/yinqiwen/ardb/issues/351

**Comment by rjonesxmoz** [comment]
Is there any way to confirm the two sets are identical or is it best to just check a random set of the key=>value results as a test?

**Comment by yinqiwen** [comment]
the only way is to save again to generate a new snapshot file and then compare the md5 checksum value.
