### ISSUE TITLE
dbsize return wrong number of key

### ISSUE THREAD

**Issue by anhduongxanh63** [yinqiwen/ardb#365]
Hi,
-dbsize: return 22596 (the same the result of command: info keyspace)
-keys *: return 425 (return a set with 425 elements)
-scan: return 425 (return a list with 425 elements)

Could you please check it.
Thank you.

**Comment by yinqiwen** [comment]
https://github.com/yinqiwen/ardb/wiki/ARDB-Commands
https://github.com/yinqiwen/ardb/issues/363

**Comment by anhduongxanh63** [comment]
Thanks for your information
