### ISSUE TITLE
Hash is stable ready for production?

### ISSUE THREAD

**Issue by anhduongxanh63** [yinqiwen/ardb#366]
Hi,
I use one hash to store map table from facebookId to userId. But sometime some key pair was lost. I dont know why.
Any thing or any configuration could cause this issue?
I really worry about this.
Please check it.
Thank you so much.

**Comment by yinqiwen** [comment]
key lost or field lost？  there is some write command which return different value than redis, that means  u can not reply on it for some complex logic.  u can disable the `redis-compatible-mode` to avoid that.

**Comment by anhduongxanh63** [comment]
Sorry, this is field lost problem.
I'm using the configuration: redis-compatible-mode yes.
and use jedis (java client) to operate with ardb.

Any advice to fix problem?
Thank you.

**Comment by anhduongxanh63** [comment]
More information:
Put field value to hash is ok, but after some days, some field values was lost.

**Comment by yinqiwen** [comment]
are u using rocksdb as the storage engine?  each hash field is actually a key in rocksdb, and there is no background task to delete a field.

**Comment by yinqiwen** [comment]
u can check  `info all` to see if there is too many `hdel` to delete the field.

**Comment by anhduongxanh63** [comment]
yes, I'm using rocksdb.
Thanks for your suggestion, I'm still tracing problem.

**Comment by anhduongxanh63** [comment]
cmdstat_hdel:calls=3,usec=2059,usecpercall=686

Just 3 command hdel used (manually used by me), hdel is not related to this problem.

**Comment by anhduongxanh63** [comment]
Hi, I just see a new problem: duplicate field in key hash.
duplicated field: 1770275339652544 (4 times)
Maybe it's related to lost field problem, please check bellow result:
10.99.0.105:15100> hgetall fb.mp
1) "1155123057954514"
  2) "494"
  3) "891489444332991"
  4) "489"
  5) "1539797929427305"
  6) "597"
  7) "10209558840147510"
  8) "596"
  9) "1326256557496411"
 10) "572"
 11) "711630019025266"
 12) "560"
 13) "10213339006780840"
 14) "563"
 15) "832576383578941"
 16) "559"
 17) "1770275339652544"
 18) "594"
 19) "10203414325195827"
 20) "604"
 21) "116297165775891"
 22) "488"
 23) "1513166762083557"
 24) "595"
 25) "1631239896894381"
 26) "600"
 27) "1227702300668583"
 28) "545"
 29) "10212520591403518"
 30) "542"
 31) "384007855351527"
 32) "552"
 33) "10212817192376156"
 34) "541"
 35) "261794604327169"
 36) "440"
 37) "10214445712526846"
 38) "441"
 39) "1522991121121451"
 40) "540"
 41) "891489444332991"
 42) "428"
 43) "10210018102872815"
 44) "539"
 45) "10155094066668892"
 46) "550"
 47) "1227347540703435"
 48) "449"
 49) "10209558840147510"
 50) "437"
 51) "1326256557496411"
 52) "444"
 53) "10213339006780840"
 54) "535"
 55) "1210726975739272"
 56) "533"
 57) "2045527769002738"
 58) "426"
 59) "10155560223944878"
 60) "534"
 61) "1303942429734081"
 62) "532"
 63) "1719515138066884"
 64) "530"
 65) "304401206691346"
 66) "425"
 67) "1499673696745269"
 68) "531"
 69) "10154810866706016"
 70) "420"
 71) "10209558840147510"
 72) "417"
 73) "1899729513614179"
 74) "422"
 75) "1644265278971673"
 76) "424"
 77) "971420332998140"
 78) "415"
 79) "1281599805285466"
 80) "413"
 81) "1570235159695481"
 82) "414"
 83) "1339363626173313"
 84) "416"
 85) "891489444332991"
 86) "408"
 87) "2009675722601713"
 88) "410"
 89) "1539797929427305"
 90) "131"
 91) "662142890651068"
 92) "139"
 93) "10209558840147510"
 94) "406"
 95) "1326256557496411"
 96) "159"
 97) "151020515481649"
 98) "391"
 99) "1634051279952146"
100) "412"
101) "1514427918577818"
102) "201"
103) "852788301536271"
104) "404"
105) "10154987405567711"
106) "407"
107) "845053098982487"
108) "44"
109) "1769909959973998"
110) "394"
111) "711630019025266"
112) "189"
113) "1304898159622695"
114) "34"
115) "10155554447533788"
116) "381"
117) "10214090574840726"
118) "395"
119) "10213339006780840"
120) "47"
121) "1969862296591124"
122) "144"
123) "251686452018136"
124) "129"
125) "1961250987455684"
126) "206"
127) "10155619100934530"
128) "118"
129) "1529473660453293"
130) "185"
131) "10154687149465025"
132) "181"
133) "1770275339652544"
134) "135"
135) "1448011065289404"
136) "82"
137) "10156774691819616"
138) "77"
139) "1717288581632491"
140) "207"
141) "803031969871156"
142) "161"
143) "10154936717612616"
144) "409"
145) "1834331016826699"
146) "383"
147) "10203414325195827"
148) "202"
149) "1535886883121713"
150) "166"
151) "1395845207119132"
152) "384"
153) "1586601918036730"
154) "175"
155) "1634787159867462"
156) "210"
157) "804617246376570"
158) "182"
159) "2143427299217494"
160) "173"
161) "1513166762083557"
162) "35"
163) "883601871795489"
164) "119"
165) "10155560223944878"
166) "114"
167) "10154838691308017"
168) "115"
169) "10212816462673940"
170) "169"
171) "10155405740891211"
172) "137"
173) "10203852995040688"
174) "72"
175) "665602626969177"
176) "71"
177) "10207688526931176"
178) "117"
179) "10154856240827467"
180) "143"
181) "833136583524460"
182) "190"
183) "478904885819011"
184) "154"
185) "10210407476077328"
186) "176"
187) "139516766645997"
188) "138"
189) "1927253984263789"
190) "393"
191) "370311170053737"
192) "186"
193) "1922465138026599"
194) "163"
195) "10155642566669198"
196) "205"
197) "1449211375164588"
198) "380"
199) "1973828972889602"
200) "101"
201) "2044335272463736"
202) "397"
203) "10209669519323993"
204) "160"
205) "272987819868935"
206) "403"
207) "493796510974729"
208) "209"
209) "1894617340865547"
210) "126"
211) "1324426087684241"
212) "212"
213) "1713511572289585"
214) "104"
215) "1540686435987876"
216) "134"
217) "1444650968958337"
218) "165"
219) "840478086108356"
220) "73"
221) "1168995859899356"
222) "142"
223) "349906952107312"
224) "103"
225) "891489444332991"
226) "43"
227) "10210018102872815"
228) "178"
229) "1496908170379370"
230) "392"
231) "10156494347628128"
232) "147"
233) "1217267278419840"
234) "177"
235) "10208223038208394"
236) "84"
237) "1539797929427305"
238) "36"
239) "1304898159622695"
240) "55"
241) "278654382615539"
242) "113"
243) "10213339006780840"
244) "47"
245) "1770275339652544"
246) "37"
247) "1448011065289404"
248) "82"
249) "1972293429680360"
250) "102"
251) "750276505144179"
252) "78"
253) "1513166762083557"
254) "35"
255) "891489444332991"
256) "192"
257) "1539797929427305"
258) "23"
259) "1770275339652544"
260) "32"

**Comment by yinqiwen** [comment]
is this from latest code ?  and which rocksdb version are u using?

**Comment by anhduongxanh63** [comment]
Thanks for your response.
it's not latest code, I cloned about 4 months ago.
RocksDB version: 5.2.1
ARDB version: 0.9.4

Thanks.

**Comment by yinqiwen** [comment]
can u using latest code  for the same data? the 'hgetall' is using rocksdb's iterator which may not ignore deleted data.

**Comment by anhduongxanh63** [comment]
Ok I will using latest code.
Thank you for your support.
