### ISSUE TITLE
Using ZINTERSTORE between a SET and a ZSET

### ISSUE THREAD

**Issue by bernardko** [yinqiwen/ardb#371]
In redis you can use ZINTERSTORE on a SET and a ZSET. 

I am trying this in ardb and its returning "WRONGTYPE Operation against a key holding the wrong kind of value.". 

Is this not supported in ardb?

**Comment by yinqiwen** [comment]
fixed in last commit

**Comment by bernardko** [comment]
Thanks for the quick response and the fix! Will rebuild and try again.

**Comment by bernardko** [comment]
Just testing it out and its working, thanks again.
