### ISSUE TITLE
Question on t_hash:MergeHSet

### ISSUE THREAD

**Issue by squalfof** [yinqiwen/ardb#372]
hi,

Within MergeHSet(), there is the predicate ```value.GetObjectLen() == -1```, 

- what's objectlen stands for here ? 
- at HSet(),  ```meta_size.SetInt64(1)``` which is assigned to object len, what's '1' here ?

Thanks.

**Comment by yinqiwen** [comment]
objectlen is the hash size stored in meta value  

meta_size.SetInt64(1) is an incr value for meta value since the 'hset' is a new field which would increase hash size.

**Comment by squalfof** [comment]
Cool.  Then what's ```meta.SetObjectLen(-1);``` used for, in both ```MergeHSet() and HMSet() ``` ?

And, seems ```HMSet()``` doesn't follow redis-protocol ? ardb uses the overwritten behavior.

**Comment by yinqiwen** [comment]
-1 mean no precise length value.
for some write commands, it's much faster if u do not care about the size value and u can use -1 instead.

there is an option `redis-compatible-mode` in ardb.conf, default value is no.

**Comment by squalfof** [comment]
then could you take a look at [code](https://github.com/yinqiwen/ardb/blob/0.9/src/command/t_hash.cpp#L108). seems no matter option ```redis-compatible-mode``` is set or not, length will set to -1.
In this case, ```HDel()``` will not remove its meta key.
Assume that's also your expected behavior ?

**Comment by yinqiwen** [comment]
for [hmset](https://redis.io/commands/hmset), the return value is just "OK", there is no need to calculate the length which could save one READ operation.
