### ISSUE TITLE
ZRemRangeByRank should use WriteBatchGuard

### ISSUE THREAD

**Issue by squalfof** [yinqiwen/ardb#376]
Please check for range del, there should be WriteBatchGuard.

Besides, why replace ```RemoveKey(ctx, field)``` with ``` iter->Del(); ``` as in [code](https://github.com/yinqiwen/ardb/blob/0.9/src/command/t_zset.cpp#L316).  If BatchGuard is employed, seems ``RemoveKey(ctx, field)``` is more appropriate ?

**Comment by yinqiwen** [comment]
u are right about the WriteBatchGuard. 
`iter->Del()` would delete a key without encoding, while `RemoveKey(ctx, field)` would encode the key to a slice.
