### ISSUE TITLE
ardb is great if it can fix one last thing...

### ISSUE THREAD

**Issue by unisqu** [yinqiwen/ardb#380]
I realised there's disk io on ardb even when it's doing nothing or nothing is being done. 

can you fix this part? it's writing to disk for no reasons whatsoever. you can check with 
watch vmstat -d

will appreciate if this can be fixed. thanks.
the need to constantly write something to disk and making the io changes is a "annoying", that's the reason it's taking up 10% CPU i think.

**Comment by yinqiwen** [comment]
is the disk io is read or write?    
there is background threads in ardb/rocksdb to do period checking task may cost some disk IO for reading.   
and if there is expired keys, ardb would do some write operations to delete them.
