### ISSUE TITLE
Question about Thread Model

### ISSUE THREAD

**Issue by squalfof** [yinqiwen/ardb#381]
hi, 
For multi-threads, seems Ardb employs multi-epoll, each epoll functions within one thread.
Why not one-epoll with a thread pool ?

Correct me if i'm wrong. Thanks.

**Comment by yinqiwen** [comment]
it's much more easy to implement a pipeline protocol(redis/http) which have no sessionId/sequeceId.

**Comment by squalfof** [comment]
Thanks. Got it.

**Comment by squalfof** [comment]
One more thing, will performance be affected if multi-epoll is employed compared with one epoll + multi threads ?

**Comment by yinqiwen** [comment]
multi-epoll:    would block all connections accepted by the same epoll  for ONE slow request.
