### ISSUE TITLE
Segmentation fault (core dumped) when running in daemon mode after compilation

### ISSUE THREAD

**Issue by unisqu** [yinqiwen/ardb#387]
Segmentation fault (core dumped) when running in daemon mode after compilation

**Comment by yinqiwen** [comment]
try make clean to recompile again

**Comment by FNST-zhoush** [comment]
Segmentation fault (core dumped) when running in daemon mode after make clean && recompile .
Version info:
ardb_version:0.9.6
redis_version:2.8.0
gcc_version:4.8.5
rocksdb_version:5.8.7

dump info:
Program terminated with signal 11, Segmentation fault.
#0  0x00000000005b7433 in ardb::Snapshot::Close (this=this@entry=0xae6f70 <ardb::_repl_singleton+560>) at repl/snapshot.cpp:1678
1678	        g_engine->ReleaseSnapshot(m_engine_snapshot);
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.6-13.el7.x86_64 glibc-2.17-105.el7.x86_64 libgcc-4.8.5-4.el7.x86_64 libstdc++-4.8.5-4.el7.x86_64 zlib-1.2.7-15.el7.x86_64
(gdb) bt
#0  0x00000000005b7433 in ardb::Snapshot::Close (this=this@entry=0xae6f70 <ardb::_repl_singleton+560>) at repl/snapshot.cpp:1678
#1  0x00000000005b760b in ardb::Snapshot::~Snapshot (this=0xae6f70 <ardb::_repl_singleton+560>, __in_chrg=<optimized out>) at repl/snapshot.cpp:1603
#2  0x00000000005cb139 in ~SlaveContext (this=0xae6ec8 <ardb::_repl_singleton+392>, __in_chrg=<optimized out>) at repl/repl.hpp:92
#3  ~Slave (this=0xae6d68 <ardb::_repl_singleton+40>, __in_chrg=<optimized out>) at repl/repl.hpp:118
#4  ardb::ReplicationService::~ReplicationService (this=0xae6d40 <ardb::_repl_singleton>, __in_chrg=<optimized out>) at repl/repl.hpp:226
#5  0x00007f7273565e69 in __run_exit_handlers () from /lib64/libc.so.6
#6  0x00007f7273565eb5 in exit () from /lib64/libc.so.6
#7  0x00000000005a593c in daemonize () at db/db.cpp:450
#8  ardb::Ardb::Init (this=this@entry=0x7ffd4fcede40, conf_file="/opt/zhoush/ardb/ardb-16377.conf") at db/db.cpp:526
#9  0x000000000040c320 in main (argc=<optimized out>, argv=<optimized out>) at main.cpp:89

#0  0x00000000005b6943 in ardb::Snapshot::Close (this=this@entry=0xad6e70 <ardb::_repl_singleton+560>) at repl/snapshot.cpp:1678
#1  0x00000000005b6b1b in ardb::Snapshot::~Snapshot (this=0xad6e70 <ardb::_repl_singleton+560>, __in_chrg=<optimized out>) at repl/snapshot.cpp:1603
#2  0x00000000005ca649 in ~SlaveContext (this=0xad6dc8 <ardb::_repl_singleton+392>, __in_chrg=<optimized out>) at repl/repl.hpp:92
#3  ~Slave (this=0xad6c68 <ardb::_repl_singleton+40>, __in_chrg=<optimized out>) at repl/repl.hpp:118
#4  ardb::ReplicationService::~ReplicationService (this=0xad6c40 <ardb::_repl_singleton>, __in_chrg=<optimized out>) at repl/repl.hpp:226
#5  0x00007fa20c835e69 in __run_exit_handlers () from /lib64/libc.so.6
#6  0x00007fa20c835eb5 in exit () from /lib64/libc.so.6
#7  0x00000000005a4e4c in daemonize () at db/db.cpp:450
#8  ardb::Ardb::Init (this=this@entry=0x7ffc94013600, conf_file="/opt/zhoush/ardb/ardb-16379.conf") at db/db.cpp:526
#9  0x000000000040b7a0 in main (argc=<optimized out>, argv=<optimized out>) at main.cpp:89

make clean && recompile, but it didn't work.  
review the code found following question:
When the parent exits parent's g_engine member in all probability is NULL .

1.    static void daemonize(void)
    {
        int fd;

        if (fork() != 0)
        {
            exit(0); /* parent exits */
        }
        ...
}
2.     void Snapshot::Close()
    {    
         ....   
       g_engine->ReleaseSnapshot(m_engine_snapshot);
        //delete ((Iterator*) m_snapshot_iter);
        m_engine_snapshot = NULL;
   }

**Comment by FNST-zhoush** [comment]
Thanks, I'll test it.
