### ISSUE TITLE
bitcount always return 0

### ISSUE THREAD

**Issue by anhduongxanh63** [yinqiwen/ardb#389]
Hi,
The first, thank you for your effort to build up ardb, we are using it in our products and it work fine so far.

I'm using bitmap to calculate report and see bitcount opration always return 0.
Could you please check it.
Thank you.

**Comment by yinqiwen** [comment]
is the ` bitcount opration always return 0` for bitcount  with start/end args?

**Comment by anhduongxanh63** [comment]
No, I use bitcount without args :)

**Comment by yinqiwen** [comment]
tested with example in https://redis.io/commands/bitcount,   it would return non zero value.

**Comment by anhduongxanh63** [comment]
That's strange, I tested with the latest code of ardb!
