### ISSUE TITLE
Do you intend to do ardbsearch like redisearch?

### ISSUE THREAD

**Issue by unisqu** [yinqiwen/ardb#395]
1. Do you intend to do ardbsearch like redisearch? Looking forward to have this feature.

2. Is there any benchmark done for hset / hget compared with redis in terms of speed?

Great work. Keep it up. Really hoping to see ardbsearch in future. Thanks

**Comment by yinqiwen** [comment]
1. i'm just start porting the module feature from redis, the development is in the `module` branch now. redisearch is just a module for redis, if this feature is done, it can be loaded& run by ardb too.
2. the performance depends on the kv storage engine rocksdb/leveldb, which definitely slower than redis in most situation. 
    for `hset`, there is ONE random kv READ & ONE kv WRITE operations. 
    for `hget`, there is ONE random kv READ operation. if the data is hit in the cache, the performance maybe very high.
