### ISSUE TITLE
Can I config the num_backups_to_keep of PurgeOldBackups or limit to max 10?

### ISSUE THREAD

**Issue by spiderpoison** [yinqiwen/ardb#399]
when we use ardb in our product, we need to back up data periodically, so we need to know when ardb has finished backup, then we can move the backup data to another place.
And If the backup folder can be named by timestamp, then it will very convenience

**Comment by yinqiwen** [comment]
currently, the folder is named as `save-rocksdb-backup.<begin offset>.<end offset>.<timestatmp>.tmp` when doing backup, and renamed to `save-rocksdb-backup.<begin offset>.<end offset>.<timestatmp>` after backup finished.

**Comment by yakexi07** [comment]
我采用最新的代码进行测试，备份名字为 save-rocksdb-backup，没有tem ，也没有timestatmp， 而且备份多次，始终是一个save-rocksdb-backup。    在实际线上使用的时候，我希望可以多次进行备份，可以保留多个备份文件，当备份数量达到最大的限制时候，删除最早的备份，请问能实现这个吗？  实际使用的时候，假如需要还原，我们也只是还原到上一个备份点的数据，中间的数据会丢失掉，是可以接受的

**Comment by yinqiwen** [comment]
are u sure using the latest code from github? 
use `git clone` to get the latest code.  and use command `save backup`  or `bgsave backup` to create  backup.
https://github.com/yinqiwen/ardb/blob/0.9/src/repl/snapshot.cpp#L2042

**Comment by yakexi07** [comment]
we get the latest code, and it work, thank you , the latest code .  what's time  the latest code released to the release version
