### ISSUE TITLE
Using lua script 

### ISSUE THREAD

**Issue by bdfy** [yinqiwen/ardb#402]
Lua scripts block everything as in Redis or not ?

**Comment by yinqiwen** [comment]
if ardb start with only one thread(configured by `thread-pool-size`), then it worked just like redis.

**Comment by craigglennie** [comment]
So, if it starts with more than one thread is it possible to have multiple commands (or Lua scripts) executing at the same time?

**Comment by yinqiwen** [comment]
@craigglennie yes
