### ISSUE TITLE
Using ardb leveldb with 1 billion test hash items

### ISSUE THREAD

**Issue by unisqu** [yinqiwen/ardb#405]
Using ardb leveldb with 1 billion test hash items, is it normal for ardb to be running with 100% cpu when nothing is running? how can I make ardb not run 100% CPU while doing nothing?

Is there a special way I can store hash items efficiently for 1 billion items?

**Comment by yinqiwen** [comment]
is there many keys with expire setting?

**Comment by unisqu** [comment]
not expire settings at all. 0 expire settings. just plain hset('1','1','a') testing dummy data sets. you can try it yourself.

**Comment by yinqiwen** [comment]
is there only ONE key to write in the test?

**Comment by unisqu** [comment]
there are 10000 keys only.
more keys better? or lesser keys?

**Comment by unisqu** [comment]
maximum size of each ldb file is around 2.3M as average, with largest as 26M, there are 6800+ files for 1 billion items. why ldb file is 2.3M? Others systems use 34mb average for 1 billion items. and will wait for the previous question's reply. Thanks.

**Comment by unisqu** [comment]
there are 10000 keys only. more keys better? or lesser keys? how to optimize for performance on the keys or ldb file size stored?

**Comment by yinqiwen** [comment]
leveldb append all writes into db first and compact later at background, more keys seems better.

and the ldb file size is a fixed value before leveldb  1.20, see this commit in leveldb https://github.com/google/leveldb/commit/a2fb086d07b7dbd9c4a59fe57646bd465841edd5#diff-6822534358e613a82db5431a19a6036f

u can upgrade leveldb to 1.20 and modify the init code here to set the max file size
 https://github.com/yinqiwen/ardb/blob/0.9/src/db/leveldb/leveldb_engine.cpp#L261

**Comment by unisqu** [comment]
it still uses 4.3% cpu and 4% memory on average for doing nothing. is this normal?

**Comment by unisqu** [comment]
How do I measure what's the maximum keys to have for hset for optimum efficiency? What's a good way to estimate maximum number of hashset values?

**Comment by yinqiwen** [comment]
it's normal, both ardb/leveldb have some background task running.

there is no limit on the number of keys or values of hash.  but if there is too much `hgetall`, it's better to keep a small number of hash values .

**Comment by unisqu** [comment]
ok thanks.
