### ISSUE TITLE
ardb备份问题

### ISSUE THREAD

**Issue by yakexi07** [yinqiwen/ardb#407]
我想问下，我在进行ardb bgsave backup的时候，数据库data文件里面sst 和 log文件，此时备份的数据库备份里面 是只有sst文件的数据库内容 吗？  还是说 此时备份就是  sst文件和log 文件的内容呢

**Comment by yinqiwen** [comment]
sst + memtable + wal

**Comment by yakexi07** [comment]
想问下，我们之前使用的是 0.9.4版本（6月份编译的），最近在升级到最新版本的时候，使用的是kill -9
 pid 的方式停掉ardb，然后启动新版本的时候，发现ardb里面的数据回档了，回档到了停止数据库之前的2个小时，想问下 出现这种情况，会是哪儿的问题啊

**Comment by yakexi07** [comment]
rocksdb.disableWAL            true , 设置了disable wal， 并且当时没有进行compactall，是否这样的情况会导致 wal 丢失呢

**Comment by yinqiwen** [comment]
是的，会丢

**Comment by yakexi07** [comment]
知道问题了，一般情况下，还是不要设置rocksdb.disableWAL true这个参数，这个会导致启动的时候丢失wal ，谢谢
