### ISSUE TITLE
Expire does not work for big object

### ISSUE THREAD

**Issue by bdfy** [yinqiwen/ardb#408]
`
#!/bin/bash

for i in {1..200000}; do
   redis-cli -p 2380 hset test tesqwejroiqwejroiqewjrewrwerlqwejroijweqiorjewiorjqoiwejrxoiqwerjqwoeirjqweoirjqweorijqorjqiwejrioqwjeriojwqeiorjqwioerjwqeiorjqwierjqweirjqwerjqweirjqwerioqwt${i} ${i} >/dev/null
   echo $i;
done

redis-cli -p 2380 expire test 100
`

redis-cli -p 2380 ttl test
(integer) -307

**Comment by bdfy** [comment]
https://github.com/yinqiwen/ardb/issues/312

**Comment by bdfy** [comment]
compactall delete this keys. But why other more smaller keys delete auto ?

**Comment by yinqiwen** [comment]
the deletion for a key is a transaction in another thread, which may slow for a large key.

**Comment by bdfy** [comment]
for 50 0000 records key was deleted after 500 seconds, for 80 000 records more than 3400 seconds ( only after hlen for key ). For big database keys were not deleted after days/month. Added compactall in cron is not beatiful solition.

**Comment by yinqiwen** [comment]
the `ttl` command would just return the ttl value for deleting keys. but if u using the `hget` command,  which would be blocked if the key is being deleting.

**Comment by bdfy** [comment]
ok - but why after run command compactall size of database decreases more than 2 times ?

**Comment by yinqiwen** [comment]
in rocksdb/leveldb, the delete/write operations are appended in db first. it u keep write/delete the same key, before background compaction completed, the db size would keep increasing.
