### ISSUE TITLE
ardb bgsave backup   crash 

### ISSUE THREAD

**Issue by yakexi07** [yinqiwen/ardb#411]
ardb version:0.9.4 
rocksdb version : rocksdb-5.2.1  

ardb 备份完成的时候出现崩溃，系统log显示如下
Feb  6 12:12:42 ip-10-33-4-71 kernel: [7190622.612230] ardb-server[10302]: segfault at 7f3147ee4290 ip 00000000006d165b sp 00007f2fef1fdb20 error 4 in ardb-server[400000+424000]

查完之后发现

[root@ip-10-33-4-71 ardb-0.9.4]# addr2line -e ./src/ardb-server  00000000006d165b
/opt/ardb/ardb-0.9.4/deps/rocksdb-5.2.1/table/block.cc:287

285     uint32_t shared, non_shared, value_length;
286     const char* key_ptr = DecodeEntry(data_ + region_offset, data_ + restarts_,
287                                       &shared, &non_shared, &value_length);
288     if (key_ptr == nullptr || (shared != 0)) {
289       CorruptionError();
290       return false;

麻烦看下是什么问题啊

**Comment by yinqiwen** [comment]
can u upgrade to latest code (git clone latest code)?  the crash is in rocksdb, the latest code already upgrade rocksdb to 5.9.2
