### ISSUE TITLE
Sorry I can't seem to find but how do I properly restart ardb instance?

### ISSUE THREAD

**Issue by unisqu** [yinqiwen/ardb#413]
Sorry I can't seem to find but how do I properly restart ardb instance? I normally kill the process and start it with a modified leveldb cache size configuration (i'm using leveldb) is this ok/normal way to do?

**Comment by yinqiwen** [comment]
just kill the process or use the redis command `shutdown`

**Comment by unisqu** [comment]
ok thanks
