### ISSUE TITLE
smembers, sinter commands are not process-safe

### ISSUE THREAD

**Issue by iseriser** [yinqiwen/ardb#420]
Using Redis->sMembers or Redis->sInter even on small sets (like 5 members) in multi process mode (32 simultaneous workers) cause protocol failures on succeeding command. i.e. hdel

Error issued by phpredis's of latest version is:
Fatal error: Uncaught RedisException: protocol error, got '1' as reply type byte
Stack trace:
#0 /the_script.php(xxx): Redis->hDel()

redis-compatible-mode setting does not affect the situation.
Script was working with no issues with original Redis 3.2.11 (Debian 8 repo).

**Comment by iseriser** [comment]
Just rewrote routine from set to hash, the same behaviour using hkeys.
Single- and multi- key commands are OK.

**Comment by iseriser** [comment]
```
    if (true) {
        while (true) {
            try {
                $pop_location = $redis->brPop("Locations", "Locations2", 0);
                break;
            } catch(\Exception $e) {
                sleep(1);
                @$redis->connect(REDIS_HOST, REDIS_PORT, REDIS_TIMEOUT);
            }
        }

        $id = 1000; $part = $pop_location[1];
        $redis->lRem($pop_location[0], $id . ":" . $part, 0);
        $head = $redis->hGet("Test" . ":" . $id . ":", $part );

        $saved_options = $redis->hKeys("Options:" . $id . ":"); // sMembers was here
    }

    if (empty($head)) {
        $redis->hDel("Test:" . $id . ":", $part); // This hDel sometimes fails in multi-process
    }
```

**Comment by iseriser** [comment]
This bug appears only if thread-pool-size is greater than 1.
Just did 1 hour stress test with 32 workers and "thread-pool-size 1", there were no exceptions.

**Comment by yinqiwen** [comment]
this seems a bug related with muli-thread notification on blocked connections. 
there is possible that a blocked connection on `brpop` would be write twice response when lpush too fast on the list.

**Comment by iseriser** [comment]
Yeah, I can confirm that replacing brPop with rPop corrects situation (based on 12 hours stress test completed). Also using brPop leads to memory leaking ended with oom-killer.

**Comment by yinqiwen** [comment]
can u test again with latest commit?
there is a possibility that a connection blocked on `brpop/blpop` would get more than one responses in multi-threading env before the commit `1a22ef1`

**Comment by iseriser** [comment]
I did 50 minutes test against your latest commit. Everything works like a charm.
No switching to pika solution ;) Thanks a lot.

**Comment by iseriser** [comment]
After 2 weeks on using with no restart, virtual memory  of the process is 25.6Gb, residential - 4.33Gb, while total size of database files is 3.0Gb. No crashes.
It seems leaking a bit.
