### ISSUE TITLE
brPop does not trigger when members appear in empty list

### ISSUE THREAD

**Issue by iseriser** [yinqiwen/ardb#421]
Using Redis->brPop in multi process mode (32 workers) started on two empty lists does not catch new ly appeared members in second list.
When script set is restarted after that situation, everything works fine (queue is being parsed normally).

This bug does not appeared on original Redis 3.2.11 (Debian 8 repo).

**Comment by yinqiwen** [comment]
are u using latest code from git or just use the code in `release`?

**Comment by iseriser** [comment]
The build was made on Feb 19 19:09 using the latest code at that moment.
