### ISSUE TITLE
Release 0.9.5 and 0.9.6

### ISSUE THREAD

**Issue by ziliangpeng** [yinqiwen/ardb#426]
Hey I'm building a ardb docker image that want to pin to a certain version of ardb (instead of pulling master). In the meantime I'd like to use the new version of ardb, but latest release is only 0.9.4

Could you please release 0.9.5 and 0.9.6? 

Thanks! 🙏

**Comment by yinqiwen** [comment]
https://github.com/yinqiwen/ardb/releases/tag/v0.9.6

**Comment by ziliangpeng** [comment]
thank you! it works.
