### ISSUE TITLE
Fields inside Hashes disappear after a short period of time when Field name is an integer

### ISSUE THREAD

**Issue by bernardko** [yinqiwen/ardb#427]
I'm am consistently getting this behaviour with ardb. I'm using a hash as an index to get an ID. Sometimes the hash field name is an integer and this is when it would disappear. I don't know the exact conditions causing this.

ex.
```
127.0.0.1:6379[5]> hset message:category_id 11300cf37f7 3385188
(integer) 1
127.0.0.1:6379[5]> hset message:category_id 19984742551 4832925
(integer) 1
127.0.0.1:6379[5]> hget message:category_id 11300cf37f7
"3385188"
127.0.0.1:6379[5]> hget message:category_id 19984742551
"4832925"
```
After a while...
```
127.0.0.1:6379[5]> hget message:category_id 11300cf37f7
"3385188"
127.0.0.1:6379[5]> hget message:category_id 19984742551
(nil)
```
This happens consistently when has field is an integer (e.g. 19984742551). But when its a string (e.g. 11300cf37f7) it remains in the hash. This doesn't seem to happen when I don't do further operations on the hash.

Any idea why this is happening?

**Comment by yinqiwen** [comment]
the latest commit fix an issue in comparator for integer https://github.com/yinqiwen/ardb/commit/fd88a52f63a0e9b99ec490a65cb969e05cfcfe38#diff-5008d1e9054cf71e83b08026b93e3ac1L278.

before this commit, if the field integer value is larger than max signed int(2147483647), there may have an integer overflow issue.

**Comment by bernardko** [comment]
Thanks @yinqiwen !

**Comment by bernardko** [comment]
Hi @yinqiwen , the problem is still happening after doing some testing. I re-added all the integer field names to the hash and over the last 2 days, they have all disappeared again.

I also tried using field names on the same hash that are outside of the scope of my application (just to make sure its not a bug in my application) and even those have disappeared as well. 

Maybe its not an integer overflow issue?

**Comment by yinqiwen** [comment]
@bernardko  can u use 'hscan' to find the missing items?

**Comment by bernardko** [comment]
@yinqiwen , I was able to locate some of the items when using HSCAN even when they don't show up when I use HGET. Some items are missing even with HSCAN though.

The following is the sample results of some keys I tried:

```
127.0.0.1:6379[5]> HSCAN message:category_id 0 match 11111111111
1) "0"
2) 1) "11111111111"
   2) "0123456789"
(5.02s)
127.0.0.1:6379[5]> HGET message:category_id 11111111111
"0123456789"
127.0.0.1:6379[5]> HSCAN message:category_id 0 match 19521268680
1) "0"
2) (empty list or set)
(4.08s)
127.0.0.1:6379[5]> HGET VendorProduct:holo_id:uidx 19521268680
(nil)
127.0.0.1:6379[5]> HSCAN message:category_id 0 match 16739804746
1) "0"
2) 1) "16739804746"
   2) "4471774"
(4.06s)
127.0.0.1:6379[5]> HGET message:category_id 16739804746
(nil)
```

For field name 11111111111, HGET was returning nil yesterday when I tried it.

For field name 19521268680, seems to be missing from both HSCAN and HGET.

For field name 16739804746, I can find it on HSCAN but HGET returns nil.

Please let me know if there is anything else you want me to test. Thanks!

**Comment by yinqiwen** [comment]
this is definite caused by the wrong comparator before.  

since the comparator changed, u should recompile the server from commit https://github.com/yinqiwen/ardb/commit/fd88a52f63a0e9b99ec490a65cb969e05cfcfe38.   And then started the server from a clean dir without any stored data.

**Comment by bernardko** [comment]
My last test was running with a server I compiled from commit fd88a52.

So I should start a clean db and re-import my data from a dump file? I'll try that out.

**Comment by bernardko** [comment]
I deleted the hash and recreated it and it seems to be working now. Closing this for now. Thanks @yinqiwen .
