### ISSUE TITLE
After prolong use i have this error.

### ISSUE THREAD

**Issue by streetlist** [yinqiwen/ardb#429]
db/version_set.cc:767: void leveldb::VersionSet::Builder::MaybeAddFile(leveldb::Version*, int, leveldb::FileMetaData*): Assertion `vset_->icmp_.Compare((*files)[files->size()-1]->largest, f->smallest) < 0' failed.

**Comment by yinqiwen** [comment]
seems related with this comparator issue  fix 
 https://github.com/yinqiwen/ardb/commit/fd88a52f63a0e9b99ec490a65cb969e05cfcfe38

**Comment by streetlist** [comment]
is leveldb recommended to use or rocksdb?
i've seen many backend systems use leveldb and i'm very comfortable with leveldb but are you also supportive of leveldb?

**Comment by streetlist** [comment]
also, because of this error, do i delete my database or i can just upgrade and use the same old database?

**Comment by yinqiwen** [comment]
it's better to delete databased first.  

rocksdb performs better with SSD disk & large memory, but it consume more memory/cpu than leveldb.   

leveldb/rocksdb are in the first class storage engine supported by ardb.

**Comment by streetlist** [comment]
do you think there will be anymore such issues in future? how stable is ardb now for production use?

**Comment by yinqiwen** [comment]
this depends on how u used it, it's stable in some very simple scenarios but may not stable in other scenarios not well tested .it's hard to tell if it's stable enough.
