### ISSUE TITLE
How was the radius-to-bits table calculated in the wiki?

### ISSUE THREAD

**Issue by umpc** [yinqiwen/ardb#430]
How was [this table](https://github.com/yinqiwen/ardb/wiki/Spatial-Index#search) calculated?

I didn't see it in-use directly in the source and didn't immediately identify what was being used to replace it. Maybe it is [this](https://github.com/yinqiwen/ardb/blob/893d2c612576368e2afec276cae4437ae4886d4d/src/common/geo/geohash_helper.cpp#L111)? The values in the table seem to work fine at a glance, though I am curious as to how they were derived.

The wiki page has been very helpful for me to learn how to optimize geohash range queries, so thank you for writing it.

**Comment by yinqiwen** [comment]
2 bits encoding represent radius value MERCATOR_MAX(20037726.37) , and when u add 2 more bit for the geohashing, the  estimate radius value would be the half of previous value.  
2  20037726.37
4  20037726.37 /2
8  20037726.37 /2 / 2
....

**Comment by umpc** [comment]
Thank you!
