### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by federicoemartinez** [yinqiwen/ardb#452]
Is it possible to build and run on windows?

**Comment by yinqiwen** [comment]
it's possible, use cygwin or mingw to build it.

**Comment by federicoemartinez** [comment]
Thanks!
I have been trying with master with Mingw without sucess.
I get:
```
common/channel/channel.cpp: In member function ‘virtual void ardb::Channel::OnWrite()’:
common/channel/channel.cpp:599:19: error: ‘sendfile’ was not declared in this scope
         int ret = sendfile(GetWriteFD(), m_file_sending->fd, &m_file_sending->file_offset, len);
```
I will try a little bit more to see if I can bypass this or try with cygwin.

**Comment by yinqiwen** [comment]
there is no `sendfile` in cygwin/mingw, it's a linux api not posix.  u can comment 'sendfile' related code  if it's just used in a single node.  the `sendfile` is only used in master to send snapshot to slave.

**Comment by federicoemartinez** [comment]
I was able to build it, but it fails when I try to add a key. I won't be able to continue with this for now. 
Thanks a lot for your help!
