### ISSUE TITLE
Compiling in Ubuntu 14.04 throws error

### ISSUE THREAD

**Issue by kidambisrinivas** [yinqiwen/ardb#91]
Hi,

Thanks for the great tool. It's an ideal tool for my use case requiring a direct replacement for redis hash with high scalability. May I check with you if the installation of this in Ubuntu 14.04 is just compiling using 'storage_engine=leveldb make'. If so, I get this error when I run a make:

g++ -c -Wall -g -O2 -fPIC -D__STDC_FORMAT_MACROS -DARDB_VERSION='"0.8.2"'  -I./ -I./common -I/home/user/projects/ds/ardb/src/../deps/cpp-btree -I/home/user/projects/ds/ardb/src/../deps/lua/src -I/home/user/projects/ds/ardb/src/../deps/snappy-1.1.2  -I/home/user/projects/ds/ardb/src/../deps/leveldb-1.16.0/include engine/leveldb_engine.cpp -o engine/leveldb_engine.o
engine/leveldb_engine.cpp: In member function ‘virtual void ardb::LevelDBLogger::Logv(const char_, __va_list_tag_)’:
engine/leveldb_engine.cpp:48:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 if (len < sizeof(logbuf))
                                        ^
echo ">>>>> Building JEMALLOC" && \
        cd /home/user/projects/ds/ardb/src/../deps && \
        tar jxf /home/user/projects/ds/ardb/src/../deps/jemalloc-3.6.0.tar.bz2 && \
        cd /home/user/projects/ds/ardb/src/../deps/jemalloc-3.6.0 && \
        patch < ../../jemalloc.patch && \
        autoconf configure.ac > configure 2> autoconf.out && \
        ./configure    > configure.out && \
        make build_lib_static && \
        echo "<<<<< Done building JEMALLOC"

> > > > > Building JEMALLOC
> > > > > patching file configure.ac
> > > > > make[1]: **\* [/home/user/projects/ds/ardb/src/../deps/jemalloc-3.6.0/lib/libjemalloc.a] Error 127
> > > > > make[1]: Leaving directory `/home/user/projects/ds/ardb/src'
> > > > > make: **\* [all] Error 2

EDIT: If this might help
OS: Ubuntu 14.04 LTS
CPU: Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
Kernel: Linux 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
gcc: gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2

Am running the build as a non-root user.

If I'm doing something wrong here, please help me with the correct way to build, install and run in ubuntu 14.04.

**Comment by amnond** [comment]
Saved me some time too, thank you :)

**Comment by luweijie007** [comment]
Saved me some time too ,and too much warn output 谢谢
